### ISSUE TITLE
gdal2 branch windows packages not uploaded

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/gdal-feedstock#10]
If this is the same as in conda-forge/wradlib-feedstock#5 I could issue the necessary PR.

**Comment by pelson** [comment]
Just needs #4 to be merged I think.

**Comment by kmuehlbauer** [comment]
@pelson Is there any guideline within conda-forge, when to merge such adminstrative stuff. Also the mentioned pr is directed into master branch not gdal2 branch. Wow do we deal with it? Merge into master and then add then apply the changes also to gdal2 branch?

**Comment by pelson** [comment]
> Also the mentioned pr is directed into master branch not gdal2 branch.

Aha! Yes, I'd forgotten. This was/is the first feedstock to have multiple branches - some of the administrative stuff won't handle multiple branches yet, I need to catch up on those cases. In the meantime, yes, I think it is wise to apply the changes from #4 into the gdal2 branch - can this be achieved cleanly by merging master into the gdal2 branch?

**Comment by kmuehlbauer** [comment]
If the two branches diverge more and more, it can be very problematic to apply automatic changes. I have just tried to create a PR from conda-forge-admin/gdal-feedstock:feedstock-renderer directly to conda-forge/gdal-feedstock:gdal2. This would work. 

If  #4 is merged before, we could try to do this pr from master to gdal2 branch. If this doesn't work out, then we can merge from conda-forge-admin. Can anybody follow?

**Comment by pelson** [comment]
Yep. Sounds sensible to me @kmuehlbauer. You have merge rights on this repo, so give it a shot! :+1:

**Comment by kmuehlbauer** [comment]
@pelson To get this right, we merge #4 now and then apply the changes to gdal2-branch.

**Comment by pelson** [comment]
Yep. 

> apply the changes to gdal2-branch.

As in:

```
git checkout -b gdal2 upstream/gdal2
git merge upstream/master
... check as expected
git push origin gdal2_pr
... create a PR which proposes the merge to gdal2 from your gdal2_pr branch
```

**Comment by kmuehlbauer** [comment]
@pelson Now we have this pr here #11. I hope, it's OK that way.

**Comment by pelson** [comment]
LGTM. Keep an eye on conda-forge channel on anaconda.org, and I suspect we can close this with no further work. :+1:

**Comment by kmuehlbauer** [comment]
FYI: The four windows python27 versions are uploaded, ... finally.

**Comment by pelson** [comment]
Phew :sweat: - we're putting AppVeyor through its paces :smile:

**Comment by kmuehlbauer** [comment]
If at first you don't succeed... :sunglasses:

**Comment by pelson** [comment]
So we can close this issue now?

**Comment by kmuehlbauer** [comment]
Yes.
