### ISSUE TITLE
Library broken on os.

### ISSUE THREAD

**Issue by hetland** [conda-forge/gdal-feedstock#100]
import gdal gives an import error:  

ImportError: dlopen(/Users/rob/anaconda/lib/python3.5/site-packages/osgeo/_gdal.so, 2): Symbol not found: __ZN6kealib10KEAImageIO10isKEAImageESs
  Referenced from: /Users/rob/anaconda/lib/python3.5/site-packages/osgeo/../../..//libgdal.20.dylib
  Expected in: /Users/rob/anaconda/lib//libkea.1.4.6.dylib
 in /Users/rob/anaconda/lib/python3.5/site-packages/osgeo/../../..//libgdal.20.dylib

**Comment by ocefpaf** [comment]
Since I don't have a Mac to test could you send me the results of:

```shell
conda create --name TEST python=3.5 gdal --channel conda-forge --yes
source activate TEST
conda info > debug.txt
conda info >> debug.txt
python -c "import gdal"
```

**Comment by dopplershift** [comment]
This just worked fine for me on OSX 10.11.

**Comment by ocefpaf** [comment]
> This just worked fine for me on OSX 10.11.

It may be a remnant from the issues we had before right before SciPy. When was your last update @hetland?

**Comment by hetland** [comment]
This test passes, but my other install of gdal (also using py35) fails. I
suspect I have conflicting package libraries somewhere, but I don't know
what the conflict could be. Relevant output from the test below:



~$ source activate TEST
(TEST) ~$ conda info > debug.txt
(TEST) ~$ conda info >> debug.txt
(TEST) ~$ python -c "import gdal"
(TEST) ~$ more debug.txt
Current conda install:

             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.5
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /Users/rob/anaconda  (writable)
  default environment : /Users/rob/anaconda/envs/TEST
     envs directories : /Users/rob/anaconda/envs
        package cache : /Users/rob/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/rob/.condarc
         offline mode : False
    is foreign system : False

Current conda install:

             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.5
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /Users/rob/anaconda  (writable)
  default environment : /Users/rob/anaconda/envs/TEST
     envs directories : /Users/rob/anaconda/envs
        package cache : /Users/rob/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/rob/.condarc
         offline mode : False
    is foreign system : False


On Tue, Jul 26, 2016 at 6:28 PM, Filipe <notifications@github.com> wrote:

> This just worked fine for me on OSX 10.11.
>
> It may be a remnant from the issues we had before right before SciPy. When
> was your last update @hetland
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_hetland&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=8u--hqNGPt7tq6ETv_nc64kyX_IPT9tbusGRejMh-7Q&s=62Gah1v3NBsdKRfukTw_39vHx-B8KKp6bqLKz0_SSWc&e=>
> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_conda-2Dforge_gdal-2Dfeedstock_issues_100-23issuecomment-2D235425791&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=8u--hqNGPt7tq6ETv_nc64kyX_IPT9tbusGRejMh-7Q&s=EQNs6Ob4A2DcnalaCQO9Hyen8sdtz_1BSQDr3AaAOs8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACesFqqeLIfw71N1MUwxYVk8Kzh-5F477Sks5qZooUgaJpZM4JVk4-5F&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=FPERNJ38ToEXgd8OyE4aew&m=8u--hqNGPt7tq6ETv_nc64kyX_IPT9tbusGRejMh-7Q&s=TNvJby_lv6MWu27EhtJSDwEMSkW5xF81eS3Ijo6R1ms&e=>
> .
>



-- 
Prof. Rob Hetland
Texas A&M Univ.  –  Dept. of Oceanography
http://pong.tamu.edu/~rob

**Comment by ocefpaf** [comment]
> This test passes, but my other install of gdal (also using py35) fails.

OK. So the issue is not here :smile: 

> I suspect I have conflicting package libraries somewhere, but I don't know
what the conflict could be. Relevant output from the test below:

That is probably `kealib`. Did you try re-creating or updating the env where the failure exist? Maybe try to update only `gdal` and `kealib` there might work.
