### ISSUE TITLE
libgdal-pdf {3.9.x,3.10.0} is not getting a proper poppler pin

### ISSUE THREAD

**Issue by akrherz** [conda-forge/gdal-feedstock#1012]
### Comment:

Looking at the [metadata](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Flibgdal-pdf-3.10.0-h697c966_2.conda) for the latest libgdal-pdf 3.10.0, we find no poppler pin

```
__glibc >=2.17,<3.0.a0
libgcc >=13
libgdal-core >=3.10
libkml >=1.3.0,<1.4.0a0
libstdcxx >=13
poppler
```

This is causing grief with #1010 and #1011 as `poppler=24.11` is a thing now.

**Comment by akrherz** [comment]
I have taken a swing at what I ignorantly think will fix this in #1011 73f2945

**Comment by akrherz** [comment]
Upstream Issue  conda-forge/poppler-feedstock#166

**Comment by xylar** [comment]
I think we will need to fix this for poppler 24.08.x as well, see https://github.com/conda-forge/poppler-feedstock/pull/169.

**Comment by xylar** [comment]
We may need to mark the earlier builds as broken but maybe let's see how it goes with those fixes first.

**Comment by akrherz** [comment]
> I wonder if the more realistic option is to migrate poppler first

I thought about that as well, but see that the bot has yet to submit a migration to pinning.  Uffties.

**Comment by xylar** [comment]
I'm fine with your solution of adding a temporary runtime constraint.

**Comment by akrherz** [comment]
> I'm fine with your solution of adding a temporary runtime constraint.

We'll see if it even works! At this point, I don't understand how conda pinning even works.

**Comment by xylar** [comment]
@akrherz, can we close this now?  I'm seeing:
```
$ conda search --info libgdal-pdf
...
libgdal-pdf 3.10.0 h10c30d1_5
-----------------------------
file name   : libgdal-pdf-3.10.0-h10c30d1_5.conda
name        : libgdal-pdf
version     : 3.10.0
build       : h10c30d1_5
build number: 5
size        : 655 KB
license     : MIT
subdir      : linux-64
url         : https://conda.anaconda.org/conda-forge/linux-64/libgdal-pdf-3.10.0-h10c30d1_5.conda
md5         : 9ea394ecad4d0b7af209a404c6193ad6
timestamp   : 2024-12-04 16:34:07 UTC
dependencies: 
  - __glibc >=2.17,<3.0.a0
  - libgcc >=13
  - libgdal-core 3.10.0 h7250d82_5
  - libkml >=1.3.0,<1.4.0a0
  - libstdcxx >=13
  - poppler >=24.11.0,<24.12.0a0
```
```
This looks good!
