### ISSUE TITLE
Are we pinning GDAL plugins correctly to libgdal-core?

### ISSUE THREAD

**Issue by akrherz** [conda-forge/gdal-feedstock#1016]
### Comment:

I am likely just driving myself crazy with understanding how pinning works, but my present doubt is how we pin plugins.  For example

libgdal-pdf
```
libgdal-core >=3.10
```

For a current example, that implies that one could install `libgdal-pdf-3.9.0` and `libgdal-core-3.10.0`:

```
$ mamba create -n dev python=3.13 libgdal-core=3.10 libgdal-pdf=3.9
  + libgdal-core                     3.10.0  h7250d82_3          conda-forge       11MB
  + libgdal-pdf                       3.9.3  hb578332_5          conda-forge      669kB

$ lib/gdalplugins/gdal_PDF.so is linked to libgdal.so.35, which does not exist.
```

Anybody with thoughts on this?

**Comment by rouault** [comment]
That's definitely wrong. Attempt at fixing that in https://github.com/conda-forge/gdal-feedstock/pull/1017
