### ISSUE TITLE
Latest version of gdal pulls in libnetcdf from default channel (built against jpeg 8d) which causes error when running

### ISSUE THREAD

**Issue by danclewley** [conda-forge/gdal-feedstock#106]
Installing the latest version of gdal (2.1.1) from conda-forge gives the following error:
```
gdal_translate: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory
```
I think this is due to pulling in libnetcdf 4.4.1 from default in preference to 4.4.0 from conda-forge.
Downgrading libnetcdf to 4.4.0 (from conda-forge) fixes gdal and doesn't change any other packages so I think this is where the problem is.

From what I can tell the version of libnetcdf in default is built against the default version of hdf4, which is built against jpeg 8d, rather than jpeg 9d used for the conda-forge hdf4 build. The version of libnetcdf from default requires hdf4 4.2.*, which the conda-forge build satisfies, but they use different versions of jpeg

Pinning gdal to use libnetcdf 4.4.0 would be the quickest solution (and I'm happy to submit a pull request for this) but I'm unsure if it is the best way to resolve.

**Comment by ocefpaf** [comment]
It is hard to debug this as we don't really know what package is causing the `jpeg` downgrade. Note that all conda-forge package are properly pinnied and this "should" should not happen. If the culprit is indeed `libnetcdf 4.4.1` you can upgrade your `conda` to the latest version, so you can have the channel preference feature, and to add conda-forge on top of `defaults` in your `.condarc` file.

Then do try:

```shell
conda create --yes -n TEST python=3.5 gdal -c conda-forge
source activate TEST
python -c "import gdal"
```

If that does not succeed send me the results of

```shell
conda info > debug.txt
conda list >> debug.txt
```

**Comment by danclewley** [comment]
OK, didn't think to check the conda version. The machine I was testing on had quite an old version (4.0.8). Updating to the latest version and running the command you suggested the correct version of `libnetcdf` gets pulled in. Reverting back to 4.0.8 (to confirm) `libnetcdf 4.4.1` gets pulled in.

I'm going to close this then as has been solved in conda and no action is needed for the gdal feedstock.

**Comment by ocefpaf** [comment]
Thanks for the tests. `conda-forge` is pushing `conda` and `conda-build` limits and new versions with improvements are released often :smile: 

The channel preference, for example, is a result of this interaction.

BTW: I am updating `libnetcdf` too. See https://github.com/conda-forge/libnetcdf-feedstock/pull/5
