### ISSUE TITLE
Windows 10 64-bit Environment Variable Path Issue with Gdal

### ISSUE THREAD

**Issue by justinmnoor** [conda-forge/gdal-feedstock#113]
Hi I am on Windows 10 (64-bit), using Anaconda3 4.1.1. I am trying to create a geospatial analysis environment in Python 2.7.12.

When attempting to install Fiona, I am having a Gdal related environment variable issue. I am told that the issue is with Gdal, not with Fiona.

I arrived here through the following steps:

1) I created an environment with 'conda create -n testenv python=2'.

2) Next I installed Fiona with 'conda install -c conda-forge fiona=1.7.0'. The following packages were installed:

![image](https://cloud.githubusercontent.com/assets/15651037/18752718/1d7dae56-8098-11e6-846b-a9e4aafc5356.png)

Fiona is supposed to take care of the environment variables. When activating my environment I get the following error:

![image](https://cloud.githubusercontent.com/assets/15651037/18752799/66ed86b0-8098-11e6-8b17-cabb8283d5cf.png)

Even if I add the Gdal dll, and the gdal-data directory, to my Windows system PATH I get the same error. Sorry if I've missed anything in the installation instructions.

Thanks

**Comment by justinmnoor** [comment]
I left Windows and I am now a very happy Ubuntu Linux user (this was building up). No more Windows issues. I'm closing this.

**Comment by gillins** [comment]
>  Linux is like magic. Goodbye Windows.

Indeed! BTW I couldn't reproduce this on Windows, I wonder if you have another `activate` in your %PATH%?
