### ISSUE TITLE
geo pdf not supported on linux

### ISSUE THREAD

**Issue by mhabets** [conda-forge/gdal-feedstock#120]
To be supported on linux, gdal must be compiled with poppler lib.
`gdal-config --dep-libs` should show: `-lpoppler`

**Comment by ocefpaf** [comment]
We do not have a conda package for `poppler`. Do you want to submit one to [`staged-recipes`](https://github.com/conda-forge/staged-recipes)?

**Comment by mhabets** [comment]
Thank you for short answer. I wish I could but I have never done that. I am afraid I can't find time to learn how to do it? Is it straightforward?

BTW, it seems there is an inconsistency with the pdf format:
- `gdalinfo --formats` returns pdf as supported: `PDF -raster,vector- (w+): Geospatial PDF`
- but `gdal_translate` and `osgeo.gdal.Translate` return `ERROR 4: 'file.pdf' not recognized as a supported file format`. The same file works well with gdal coming with the ubuntu package.

**Comment by gillins** [comment]
Just to clarify - it seems that PDF write support is included by default, read support needs another library (`poppler` etc). See http://www.gdal.org/frmt_pdf.html and http://gdal.org/formats_list.html.

**Comment by ocefpaf** [comment]
>  read support needs another library

@pkg added `poppler` some time ago (thanks!), and I added it as a dependency in https://github.com/conda-forge/libgdal-feedstock/pull/3
