### ISSUE TITLE
libicui18n.so.56 not found, python 3.4, gdal 2.1.2

### ISSUE THREAD

**Issue by davidh-ssec** [conda-forge/gdal-feedstock#145]
Get this error when attempting to build my package that requires python 3.4 and ends up using conda-forge's gdal 2.1.2 on OSX and Linux (haven't tested windows yet):

```
    import gdal, osr
  File "/Users/davidh/anaconda/conda-bld/sift_1486418516088/_t_env/lib/python3.4/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/Users/davidh/anaconda/conda-bld/sift_1486418516088/_t_env/lib/python3.4/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/davidh/anaconda/conda-bld/sift_1486418516088/_t_env/lib/python3.4/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/Users/davidh/anaconda/conda-bld/sift_1486418516088/_t_env/lib/python3.4/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
ImportError: dlopen(/Users/davidh/anaconda/conda-bld/sift_1486418516088/_t_env/lib/python3.4/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/libicui18n.56.dylib
  Referenced from: /Users/davidh/anaconda/conda-bld/sift_1486418516088/_t_env/lib/libgdal.20.dylib
  Reason: image not found
```

I'm guessing since conda-forge no longer supports python 3.4 I'm SOL? I can't seem to find a version that works anymore since forcing the version that worked before (2.1.1) leads to:

```File "/Users/davidh/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 379, in verify_specs
    raise NoPackagesFoundError(bad_deps)
conda.exceptions.NoPackagesFoundError: Dependencies missing in current osx-64 channels: 
  - my_pkg -> gdal ==2.1.1 -> proj.4
  - gdal ==2.1.1 -> proj.4
```

Any help is much appreciated.

**Comment by ocefpaf** [comment]
Python 3.4 is no longer supported in `conda-forge` and we also moved the `icu` from `56.*` to icu `58.*`. You are probably seeing that error because you are getting an old build of  `gdal`, pinned to `icu 56.* `, but the rest of the dependencies forced `icu 58.*` to be installed.

You options are to either move to Python 3.5 or 3.6, or to pin `icu 56.*` (and probably `libxml2 2.9.3` too) in your work env.

Closing this because we cannot do another Python 3.4 build because the CIs cannot handle that and we chose to move to Python 3.6.

**Comment by davidh-ssec** [comment]
Thanks I figured, but limiting those package versions doesn't seem to help.

**Comment by ocefpaf** [comment]
> Thanks I figured, but limiting those package versions doesn't seem to help.

Can you share your setup? I can check what else may need to be pinned.

**Comment by davidh-ssec** [comment]
```ImportError: dlopen(/Users/davidh/anaconda/conda-bld/sift_1486421633282/_t_env/lib/python3.4/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Users/davidh/anaconda/conda-bld/sift_1486421633282/_t_env/lib//libdap.23.dylib
  Reason: image not found```

And it tries to install the following packages on build (sorry, long):

```
The following NEW packages will be INSTALLED:

    affine:          2.0.0.post1-py34_0                 conda-forge                             
    blas:            1.1-openblas                       conda-forge                             
    boto3:           1.4.2-py34_0                       conda-forge                             
    botocore:        1.4.81-py34_0                      conda-forge                             
    ca-certificates: 2016.9.26-0                        conda-forge                             
    certifi:         2017.1.23-py34_0                   conda-forge                             
    click:           6.6-py34_1                         conda-forge                             
    click-plugins:   1.0.3-py34_0                       conda-forge                             
    cligj:           0.4.0-py34_0                       conda-forge                             
    curl:            7.52.1-0                           conda-forge                             
    cycler:          0.10.0-py34_0                      conda-forge                             
    docutils:        0.12-py34_0                        conda-forge                             
    expat:           2.1.0-2                            conda-forge                             
    freetype:        2.6.3-1                            conda-forge                             
    freexl:          1.0.2-1                            conda-forge                             
    gdal:            2.1.2-np111py34_6                  conda-forge                             
    geos:            3.5.1-1                            conda-forge                             
    giflib:          5.1.4-0                            conda-forge                             
    h5py:            2.6.0-np111py34_7                  conda-forge                             
    hdf4:            4.2.12-0                           conda-forge                             
    hdf5:            1.8.17-9                           conda-forge                             
    icu:             56.1-4                             conda-forge                             
    jmespath:        0.9.0-py34_0                       conda-forge                             
    jpeg:            9b-0                               conda-forge                             
    json-c:          0.12-0                             conda-forge                             
    kealib:          1.4.6-3                            conda-forge                             
    libdap4:         3.18.3-2                           conda-forge                             
    libgfortran:     3.0.0-0                            conda-forge                             
    libiconv:        1.14-4                             conda-forge                             
    libnetcdf:       4.4.1.1-2                          conda-forge                             
    libpng:          1.6.28-0                           conda-forge                             
    libpq:           9.5.4-3                            conda-forge                             
    libspatialite:   4.3.0a-14                          conda-forge                             
    libtiff:         4.0.6-7                            conda-forge                             
    libxml2:         2.9.3-9                            conda-forge                             
    llvmlite:        0.15.0-py34_0                                                              
    matplotlib:      2.0.0-np111py34_1                  conda-forge                             
    ncurses:         5.9-10                             conda-forge                             
    netcdf4:         1.2.7-np111py34_0                  conda-forge                             
    numba:           0.30.1-np111py34_0                                                         
    numpy:           1.11.3-py34_blas_openblas_200      conda-forge                              [blas_openblas]
    olefile:         0.42.1-py34_1                      conda-forge                             
    openblas:        0.2.19-0                           conda-forge                             
    openjpeg:        2.1.2-2                            conda-forge                             
    openssl:         1.0.2h-3                           conda-forge                             
    pcre:            8.39-0                             conda-forge                             
    pillow:          4.0.0-py34_0                       conda-forge                             
    pip:             9.0.1-py34_0                       conda-forge                             
    proj4:           4.9.3-2                            conda-forge                             
    pyopengl:        3.1.0-py34_0                       conda-forge                             
    pyparsing:       2.1.10-py34_0                      conda-forge                             
    pyproj:          1.9.5.1-py34_0                     conda-forge                             
    pyqt:            4.10.4-py34_0                                                              
    pyshp:           1.2.1-py34_0                       <local url>
    python:          3.4.5-2                            conda-forge                             
    python-dateutil: 2.6.0-py34_0                       conda-forge                             
    pytz:            2016.10-py34_0                     conda-forge                             
    qt:              4.8.5-3                                                                    
    rasterio:        1.0a5-np111py34_0                  conda-forge                             
    readline:        6.2-0                              conda-forge                             
    s3transfer:      0.1.9-py34_0                       conda-forge                             
    scipy:           0.18.1-np111py34_blas_openblas_201 conda-forge                              [blas_openblas]
    setuptools:      32.3.1-py34_0                      conda-forge                             
    shapely:         1.5.11-py34_0                      <local url>
    sift:            0.9.0a0-1                          local                                   
    sip:             4.15.5-py34_0                                                              
    six:             1.10.0-py34_1                      conda-forge                             
    snuggs:          1.4.1-py34_0                       conda-forge                             
    sqlite:          3.13.0-1                           conda-forge                             
    tk:              8.5.19-1                           conda-forge                             
    vispy:           0.5.0dev2-py34_1                   local                                   
    wheel:           0.29.0-py34_0                      conda-forge                             
    xerces-c:        3.1.4-2                            conda-forge                             
    xz:              5.2.2-0                            conda-forge                             
    zlib:            1.2.11-0                           conda-forge    
```

Both pyshp and shapely are using versions stored on a local server since originally we had trouble getting a version that wasn't broken on all platforms. I've tried removing those dependencies and it still fails.

**Comment by ocefpaf** [comment]
> And it tries to install the following packages on build (sorry, long):

I meant the setup to build your package. A recipe or a list of dependencies. But the error tells me that you will need an older `libdap4` too. Try: `libdap4 3.18.2`

**Comment by davidh-ssec** [comment]
Ah thanks. Here's my meta.yaml requirements. Not sure if I still have to list them for both build and run, but I still do that. My package is all python, just lots of dependencies. Any weird version restrictions are mostly because at some point in time the package had errors when installing them:

```
  build:
    - python >=3.4
    - setuptools
    - numpy >=1.11
    - matplotlib
    - scipy
    - numba >=0.30
    - pyproj >=1.9.4
    - pyopengl
    - netcdf4
    - h5py
    - pillow
    - pyshp >=1.2.1
    - shapely >=1.5.11
    - rasterio
    - gdal >=2.1 # [win]
    - libgdal >=2.1 # [win]
    - gdal >=2.1.0 # [unix]
    - pyqt ==4.10.4
    - cython >=0.17 # [win]
    # Only needed for pillow 4.0.0_0-py34, remove  after any of those change
    - olefile
    - libdap4 <=3.18.2
```

**Comment by davidh-ssec** [comment]
FYI with that libdap4 restriction I get:

```
ImportError: dlopen(/Users/davidh/anaconda/conda-bld/sift_1486424752482/_t_env/lib/python3.4/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/libicui18n.56.dylib
  Referenced from: /Users/davidh/anaconda/conda-bld/sift_1486424752482/_t_env/lib/libgdal.20.dylib
  Reason: image not found
```

**Comment by ocefpaf** [comment]
Did you add `icu 56.*` in your tests? (I don't see it there.)
I would also remove `libgdal` on Windows. The `gdal` package from conda-forge is `gdal`+`libgdal`. That is probably another source of headaches.

Another thing that catches my eye is `pyqt ==4.10.4`. In conda-forge we use `4.11.*` and that one is probably from `defaults`, bring another `qt4`, and another set of possible incompatibilities.

If you have that in a repo or if you can share the whole recipe I can make a few tests and find a combination that works for Python 3.4. But I do recommend you to move to Python >=3.5.

**Comment by davidh-ssec** [comment]
> Did you add icu 56.* in your tests? (I don't see it there.)

Oh duh, I removed it while testing other stuff. After putting `icu <57` and keeping the `libdap4` restriction I was able to build a package and import it on OSX.

For the pyqt restriction, iirc that was due to a missing library problem that only existing on Windows or something.

We had plans of upgrading to a newer python (honestly in our field using python 3 is still rather new), but some of our users run a simple script that blindly updates our application package via conda. Since we can't easily have them update the version of python it requires some hand holding to recreate their environments with python 3.6. I think I've got it from here. Thanks so much.

**Comment by ocefpaf** [comment]
> Oh duh, I removed it while testing other stuff. After putting `icu <57` and keeping the `libdap4` restriction I was able to build a package and import it on OSX.

:+1: 

> For the pyqt restriction, iirc that was due to a missing library problem that only existing on Windows or something.

The `qt`/`pyqt`package in conda-forge is quite new, and we don't have an OS X version yet, so I recommend you to try it.

> We had plans of upgrading to a newer python (honestly in our field using python 3 is still rather new), but some of our users run a simple script that blindly updates our application package via conda. Since we can't easily have them update the version of python it requires some hand holding to recreate their environments with python 3.6. I think I've got it from here. Thanks so much.

I understand that. As I dev I only use Python 3, but as an oceanographer I am stuck with Python 2.7.

> Edit: We are switching to python 3.6 but were hoping to get one more release out before that.

:+1:

**Comment by michaelaye** [comment]
See the same error with python 3.6 and icui18n.58 now?

```bash
ImportError: dlopen(/Users/chha0593/anaconda/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Users/chha0593/anaconda/lib/libgdal.20.dylib
  Reason: image not found
```

**Comment by michaelaye** [comment]
most likely standard prob of mixing defaults with conda-forge. will try conda-forge only.

**Comment by gilliM** [comment]
@michaelaye Did you fix it ? I tried a lot of options already...
