### ISSUE TITLE
Enabling LibKML Driver

### ISSUE THREAD

**Issue by gvellut** [conda-forge/gdal-feedstock#152]
I am using GDAL on Windows 10 with a Python 2.7 32bit environment. My GDAL env entry is: 
> conda-forge::gdal=2.1.3=np111py27_vc9_0

I noticed the KML driver used by OGR is still the old / standard one (http://www.gdal.org/drv_kml.html). 
With ogrinfo --formats :
> KML -vector- (rw+v): Keyhole Markup Language (KML)

Is there a possibility of including the LibKML driver for OGR (http://www.gdal.org/drv_libkml.html) as well in the future ? It has some nice enhancements like support for reading and writing SimpleData tags. Thanks.

**Comment by ocefpaf** [comment]
I am not familiar with this driver. Do you know if that is only a compiler flag option that needs to be on? Or do we need to package another library and link to it? If you know what is necessary to enable do you want to try a PR?

**Comment by gvellut** [comment]
Here is what the LibKML driver page says :

> The LIBKML driver is a client of [Libkml ](https://github.com/google/libkml) from Google, a reference implementation of KML reading and writing, in the form of a cross platform C++ library. You must build and install Libkml in order to use this OGR driver.

So yes there is indeed an additional dependency, not just a flag.
I will try a PR.

**Comment by ocefpaf** [comment]
> I will try a PR.

Thanks. We fist need the dependency as a feedstock, so we need a PR to https://github.com/conda-forge/staged-recipes

(Let me know if you are not familiar with conda-forge details.)

**Comment by ocefpaf** [comment]
Should be working now, see https://github.com/conda-forge/libgdal-feedstock/pull/3
