### ISSUE TITLE
Install of 2.1.3 and 2.2.0 broken because of a lack of dependency on icu

### ISSUE THREAD

**Issue by microe** [conda-forge/gdal-feedstock#158]
If one installs the gdal conda package, the libgdal.so will have trouble finding the icu library:
```
$ldd /work/ehovland/anaconda/4.3.0-py36/lib/libgdal.so | grep 'not found'
        libicui18n.so.58 => not found
        libicuuc.so.58 => not found
        libicudata.so.58 => not found
        libicui18n.so.58 => not found
        libicuuc.so.58 => not found
        libicudata.so.58 => not found
        libicui18n.so.58 => not found
        libicuuc.so.58 => not found
        libicudata.so.58 => not found
        libicui18n.so.58 => not found
        libicuuc.so.58 => not found
        libicudata.so.58 => not found
```

Installing the icu package fixes this:
```
$ldd /work/ehovland/anaconda/4.3.0-py36/lib/libgdal.so | grep icu
        libicui18n.so.58 => /work/ehovland/anaconda/4.3.0-py36/lib/./libicui18n.so.58 (0x00007fa083f56000)
        libicuuc.so.58 => /work/ehovland/anaconda/4.3.0-py36/lib/./libicuuc.so.58 (0x00007fa083b56000)
        libicudata.so.58 => /work/ehovland/anaconda/4.3.0-py36/lib/./libicudata.so.58 (0x00007fa082056000)
```

The gdal conda package should depend on icu so that this dependency can be met at installation time.

**Comment by ocefpaf** [comment]
This looks like a case of http://conda-forge.github.io/docs/conda-forge_gotchas.html#using-multiple-channels

Can you check if you have an updated conda, with the channel preference feature, and that you have the conda-forge on top of `defaults`?

**Comment by ocefpaf** [comment]
Closing this because we don't really need to specify `icu` in `gdal` from `conda-forge`. Please let me know if the info above helped you to solve this issue on your end.

**Comment by microe** [comment]
I appreciate the advice.

I did this:
```
ehovland@mage:anaconda-install$conda config --show
channels:
  - conda-forge
  - defaults
```

Using ```conda config --system --prepend channels conda-forge```.

When I try to install gdal:
```
$conda install --dry-run -v gdal
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /work/ehovland/anaconda/4.3.0-py36:

The following NEW packages will be INSTALLED:

    freexl:        1.0.2-1           conda-forge
    gdal:          2.2.0-np111py36_0 conda-forge
    geos:          3.5.1-1           conda-forge
    giflib:        5.1.4-0           conda-forge
    hdf4:          4.2.12-0          conda-forge
    json-c:        0.12-0            conda-forge
    kealib:        1.4.7-1           conda-forge
    krb5:          1.14.2-0          conda-forge
    libdap4:       3.18.3-2          conda-forge
    libnetcdf:     4.4.1.1-4         conda-forge
    libpq:         9.5.4-4           conda-forge
    libspatialite: 4.3.0a-15         conda-forge
    openjpeg:      2.1.2-2           conda-forge
    proj4:         4.9.3-3           conda-forge
    util-linux:    2.21-0                       
    xerces-c:      3.1.4-0                      

The following packages will be UPDATED:

    anaconda:      4.3.0-np111py36_0             --> custom-py36_0            
    libpng:        1.6.27-0                      --> 1.6.28-0      conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:         4.3.8-py36_0                  --> 4.2.13-py36_0 conda-forge
    conda-env:     2.6.0-0                       --> 2.6.0-0       conda-forge
```

So I am either not doing the right thing or this doesn't work.

**Comment by microe** [comment]
Any consideration to versioning the xerces-c dependency so that version 3.1.4-3 is looked for and hopefully picked up from conda-forge?

**Comment by ocefpaf** [comment]
Are you using the Anaconda distribution and trying to install it in the root env?
Try a fresh env instead, this should avoid clashing with Anaconda's distro packages.

`conda create -n GDAL python=3.6 gdal`

**Comment by microe** [comment]
Yes, I am using the Anaconda distribution and I am trying to install it into the root env.

I have already tried the fresh env route and although that works by example, I have some constraints that make it more helpful to use the distribution. I wanted to see if all options were exhausted to get this to work upstream before doing my own workarounds.

**Comment by ocefpaf** [comment]
> I have some constraints that make it more helpful to use the distribution.

Sorry but `conda-forge` packages are not 100% compatible with the Anaconda distro and you won't be able to make that work. We do recommend the use of `miniconda` when adding `conda-forge` as your preferred channel to avoid such issues.
