### ISSUE TITLE
Having issues installing fiona from conda-forge, looks related to conda-forge gdal install

### ISSUE THREAD

**Issue by nickeubank** [conda-forge/gdal-feedstock#16]
Can't seem to get a working `conda` build of fiona in a development environment in osx (works fine in root environment). I *think* it's a gdal issue. Here's the output:

    conda create -y --name test_fiona3 python=3.4
    Fetching package metadata: ....
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona3:

    The following NEW packages will be INSTALLED:

        openssl:    1.0.2g-0      defaults
        pip:        8.1.1-py34_0  defaults
        python:     3.4.4-0       defaults
        readline:   6.2-2         defaults
        setuptools: 20.3-py34_0   defaults
        sqlite:     3.9.2-0       defaults
        tk:         8.5.18-0      defaults
        wheel:      0.29.0-py34_0 defaults
        xz:         5.0.5-1       defaults
        zlib:       1.2.8-0       defaults

    Linking packages ...
    [      COMPLETE      ]|#############################################################################################| 100%
    #
    # To activate this environment, use:
    # $ source activate test_fiona3
    #
    # To deactivate this environment, use:
    # $ source deactivate
    #
    ➜  ~ source activate test_fiona3
    discarding /Users/Nick/anaconda/bin from PATH
    prepending /Users/Nick/anaconda/envs/test_fiona3/bin to PATH
    (test_fiona3)➜  ~ conda install -y -c conda-forge fiona
    Fetching package metadata: ......
    Solving package specifications: .........

    Package plan for installation in environment /Users/Nick/anaconda/envs/test_fiona3:

    The following NEW packages will be INSTALLED:

        click:         6.3-py34_0         defaults   
        click-plugins: 1.0.3-py34_0       conda-forge
        cligj:         0.4.0-py34_0       defaults   
        curl:          7.45.0-0           defaults   
        fiona:         1.6.3-np110py34_0  conda-forge
        gdal:          1.11.4-np110py34_0 conda-forge
        geos:          3.4.2-0            conda-forge
        hdf4:          4.2.11-0           defaults   
        hdf5:          1.8.15.1-2         defaults   
        jbig:          2.1-0              defaults   
        jpeg:          8d-1               defaults   
        kealib:        1.4.5-0            defaults   
        krb5:          1.13.2-0           defaults   
        libnetcdf:     4.3.3.1-3          defaults   
        libpng:        1.6.17-0           defaults   
        libtiff:       4.0.6-1            defaults   
        mkl:           11.3.1-0           defaults   
        munch:         2.0.4-py34_0       conda-forge
        numpy:         1.10.4-py34_0      defaults   
        openjpeg:      2.1.0-1            conda-forge
        proj.4:        4.9.1-2            conda-forge
        six:           1.10.0-py34_0      defaults   
        xerces-c:      3.1.2-0            defaults   

    Linking packages ...
    [      COMPLETE      ]|#############################################################################################| 100%
    (test_fiona3)➜  ~ python -c 'import fiona'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/__init__.py", line 72, in <module>
        from fiona.collection import Collection, BytesCollection, vsi_path
      File "/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/collection.py", line 7, in <module>
        from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
    ImportError: dlopen(/Users/Nick/anaconda/envs/test_fiona3/lib/python3.4/site-packages/fiona/ogrext.so, 2): Library not loaded: /usr/local/lib/libgif.4.1.6.dylib
      Referenced from: /Users/Nick/anaconda/envs/test_fiona3/lib/libgdal.1.dylib
      Reason: image not found
    (test_fiona3)➜  ~ 

Any thoughts? [Cross-listed in Fiona-feedstock.](https://github.com/conda-forge/fiona-feedstock/issues/1)

**Comment by pelson** [comment]
Looking at it, I think the correct location is probably the fiona feedstock, but let's wait to see if we can get a resolution before closing this.

**Comment by ocefpaf** [comment]
@nickeubank I believe this was sorted out. Please let us know if you find any issues with the GIS software stack in conda-forge.
