### ISSUE TITLE
libgdal linked to older gdal

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/gdal-feedstock#165]
The conda-forge upgrade for libgdal (2.2.1.0) just downgraded my gdal from 

2.2.0-np112py36_3 

to 

2.2.0-np112py36_2

Just checking if that was intentional?

**Comment by ocefpaf** [comment]
The `gdal` package for 2.2.1 is probably not in the channel yet. There is some transition time now that we have two different packages. However, I believe that build number downgrade is completely unrelated b/c a `libgdal` version can only be installed with the same `gdal` version.
