### ISSUE TITLE
numpy types not accepted, explicit casting to Python builtin types necessary

### ISSUE THREAD

**Issue by megies** [conda-forge/gdal-feedstock#167]
I'm a bit unsure were to report this upstream, as the gdal site seems really C-oriented and this is a pure Python-implementation issue..  can you please let me know where to best report the following issue?

Several `gdal` methods that operate with accept integer/float types raise exceptions with very strange error messages when numpy types are fed to them. For the user an explicit type casting is necessary and in some cases it is even worse because the user can be lead to assume that a floating point object is not accepted which implicitly suggests that an integer value has to be provided.

Here is a short example of creating a geotiff file from a numpy array:

```python
import numpy as np
from osgeo import gdal, osr

# simple 2x2 array data, integer type, but data statistics will be float
data = np.array([0, 0, 0, 1], dtype=np.int32).reshape((2, 2))
# shape of the array in numpy types will raise an error when creating the Dataset
nx, ny = map(np.int32, data.shape)

driver = gdal.GetDriverByName('GTiff')

# ------->  first problem
# XXX first occasion that can be problematic if in custom workflows number of
# XXX points happens to be in numpy types:
ds = driver.Create('/tmp/gdal_bug.tif', nx, ny, 1, gdal.GDT_Int32)
# XXX using the folowing line instead works,
# XXX casting the x/y grid point numbers to Python builtin int:
#ds = driver.Create('/tmp/gdal_bug.tif', int(nx), int(ny), 1, gdal.GDT_Float32)
srs = osr.SpatialReference()
# EPSG reference system is from Germany
srs.ImportFromEPSG(31468)
ds.SetProjection(srs.ExportToWkt())
lower_left_easting = 4465000  # in meters-based CRS
lower_left_northing = 5320000  # in meters-based CRS
grid_spacing = 1000  # in meters
gt = [lower_left_easting, grid_spacing, 0,
      lower_left_northing, 0, grid_spacing]
ds.SetGeoTransform(gt)
outband = ds.GetRasterBand(1)

# ------->  second problem
# XXX second occasion that can be problematic if in custom workflows number of
# XXX points happens to be in numpy types:
# XXX using numpy routines to prepare data statistics often results in numpy
# XXX types and causes the following routine to fail
# XXX even worse: the error message suggests that a type casting from float to
# XXX int type is necessary to set the band statistics (which makes the statistics
# XXX plain wrong)
outband.SetStatistics(
    np.min(data), np.max(data),
    np.average(data), np.std(data))
# XXX using the folowing line instead works:
#outband.SetStatistics(
#    float(np.min(data)), float(np.max(data)),
#    float(np.average(data)), float(np.std(data)))
outband.WriteArray(data)
# dereference to flush data to disk
# https://trac.osgeo.org/gdal/wiki/PythonGotchas
outband = None
ds = None
```

In two places, providing numpy int/float data types will raise strange error messages while a simple cast to the equivalent Python builtin int/float type solves the problem.

In the first problem (using numpy integer types for the raster band x/y grid point numbers) shows the following message:

```
Traceback (most recent call last):
  File "gdal_error.py", line 13, in <module>
    ds = driver.Create('/tmp/gdal_bug.tif', nx, ny, 1, gdal.GDT_Int32)
  File "/home/megies/anaconda/envs/default/lib/python2.7/site-packages/osgeo/gdal.py", line 1533, in Create
    return _gdal.Driver_Create(self, *args, **kwargs)
TypeError: in method 'Driver_Create', argument 3 of type 'int'
```

In the second problem (which is an extremely likely scenario for users -- calculating data stats using numpy), providing numpy float types to set the band statistics fails with a completely misleading error that suggests that a float type is not acceptable as input:

```
Traceback (most recent call last):
  File "gdal_error.py", line 37, in <module>
    np.average(data), np.std(data))
  File "/home/megies/anaconda/envs/default/lib/python2.7/site-packages/osgeo/gdal.py", line 2345, in SetStatistics
    return _gdal.Band_SetStatistics(self, *args)
TypeError: in method 'Band_SetStatistics', argument 2 of type 'double'
```

**EDIT**: Version numbers:
```
gdal                      2.2.1               np113py27_0    conda-forge
libgdal                   2.2.1                         1    conda-forge
```

**Comment by ocefpaf** [comment]
> I'm a bit unsure were to report this upstream, as the gdal site seems really C-oriented and this is a pure Python-implementation issue..

I believe that this is indeed an upstream issue. The swig auto-generated python bindings are supported.

BTW did you try to `rasterio`? It should be much easier to use than `gdal`'s python bindings.

**Comment by gillins** [comment]
Or try `rios` :smile:

**Comment by megies** [comment]
Thanks for the refs to `rasterio` and `rios`, I'll check it out when I have more time. Currently I only have some simple use cases of e.g. creating geotiff from numpy arrays or shapefiles from dictionary-like object collections. For these I have some code snippets I've been using for quite a while, so I'm not gonna change my running system right now. But I'll definitly check those other projects out when I have to do something new..
