### ISSUE TITLE
ImportError: dlopen(/Users/name/anaconda/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/libjpeg.8.dylib

### ISSUE THREAD

**Issue by scienceyogi** [conda-forge/gdal-feedstock#177]
So I've had to install GDAL on 6 computers in the last month, I had this down to an art, but all of the sudden, my fool-proof install stopped working. Here is what I did:

Install Anaconda
conda update conda

```
### NOTE: if you have a warning like: If the requested url is in fact a valid conda channel, please request that the channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json
Delete ALL anaconda files, including those that are “hidden” (e.g., .conda, .ipython, etc.) and reinstall Anaconda

conda config --add channels conda-forge
conda install -c conda-forge gal
conda install gdal
```

In the past when I fumbled through gdal installs I had to install jpeg - tried that. Nothing.

**Comment by ocefpaf** [comment]
Please take a look at https://conda-forge.org/docs/conda-forge_gotchas.html

**Comment by scienceyogi** [comment]
For the record:

conda config --add channels conda-forge

Puts channels in the right order.

What worked? (the final comment in document)
"In addition to the channel priority we recommend to always install your packages inside a new environment instead the root environment from anaconda/miniconda. Using envs make it easier to debug problems with packages and ensure the stability of your root env."

**Comment by ocefpaf** [comment]
> For the record:
conda config --add channels conda-forge
Puts channels in the right order.

The docs are not only about the channel order, please see the note regarding the use of anaconda distribution and the bundled software that comes with it.

> What worked? (the final comment in document)

Yep. Forcing install `jpeg` is not the answer. one need a clean slate to avoid "confusing" the conda solver.
