### ISSUE TITLE
Mismatch between gdal and libgdal on current Win conda-forge install

### ISSUE THREAD

**Issue by jgomezdans** [conda-forge/gdal-feedstock#181]
Trying to install gdal from conda-forge results in a missing library issue on Windows 10. Upon closer inspection, it's the same problem reported [here](https://github.com/ContinuumIO/anaconda-issues/issues/1687), in a nutshell that you install different versions of gdal and libgdal. You can solve it by installing gdal and making sure you also install libgdal=2.2.2 (e.g. specifying the libgdal version to match that of gdal).

**Comment by ocefpaf** [comment]
That is unfortunate. I had only "gdal" in the past to avoid that mismatch and conda refuses to obey the pinning there :unamused: 

I don't have a solution for you. Sometime the instructions [here](https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels) help.

I am closing as won't fix b/c there is nothing we can do at the moment.
In theory moving to `conda-build 3` will help with those issues.
