### ISSUE TITLE
Install of GDAL with conda fails

### ISSUE THREAD

**Issue by akgjertsen** [conda-forge/gdal-feedstock#183]
GDAL will not work after installing with
`conda config --add channels conda-forge`
`conda install gdal`

I have a new Anaconda installed: 
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:34:40) [MSC v.1500 64 bit (AMD64)] on win32 and conda 4.3.29 on a Windows 10 machine. (Version 1703 (OS-build 15063.674).

The error message I get is:

```
>>> from osgeo import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\argj\AppData\Local\Continuum\anaconda2\lib\site-packages\osgeo\__init__.py", line 25, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\argj\AppData\Local\Continuum\anaconda2\lib\site-packages\osgeo\__init__.py", line 21, in swig_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: Den angitte modulen ble ikke funnet.

```
I installed an earlier Version of GDAL (2.1.0), then I got another error. It finds no driver for jp2 files.

```
Python 2.7.14 | packaged by conda-forge | (default, Oct  5 2017, 15:28:58) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> gdal.Open(r'e:\temp\L2A_T32VPM_20170811T104021_B02_10m.jp2')
ERROR 4: `e:\temp\L2A_T32VPM_20170811T104021_B02_10m.jp2' not recognized as a supported file format.

```
On my old PC with Windows 7 I installed GDAL with conda and had no problems. 

**Workaround**
I tried to install with PIP instead. I downloaded a GDAL Wheel and installed it with 
`pip install GDAL 2.2.2 cp27 cp27m win_amd64.whl `
and with this method I have no problems.

```
(root) C:\Users\argj>python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 15 2017, 03:34:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from osgeo import gdal
>>> ds = gdal.Open(r'e:\temp\L2A_T32VPM_20170811T104021_B02_10m.jp2')
>>> ds.GetDescription()
'e:\\temp\\L2A_T32VPM_20170811T104021_B02_10m.jp2'
```

I prefer to use conda to install packages, and I hope that this issue can be solved. 

Thanks!

**Comment by ocefpaf** [comment]
I see you are using the anaconda distribution. Are you installing `gdal` in the root environment? That won't work due to all the pre-installed packages bundled in the anaconda distribution. Can you try installing `gdal` in a new environment and test it? For example:

```
conda create --name TEST python=3.6 gdal
activate TEST
python -c "from osgeo import gdal"
```

See https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels for more info.

PS: When using `gdal 2.1.0` you got a driver error. I am not sure our version has the driver to read `jp2` files. I'll check that.

**Comment by ocefpaf** [comment]
I can read a `j2k` file, which I assume is similar to `jp2`, on Linux.
Can you provide a simple `jp2` so I can add it as a test in the CIs? That way we can check if it works on Windows and OS X too.

**Comment by akgjertsen** [comment]
I have now tested what you suggests. But I get the same error.

```
(TEST) C:\Users\argj>conda env list
# conda environments:
#
GDAL                     C:\Users\argj\AppData\Local\Continuum\anaconda2\envs\GDAL
GDAL2                    C:\Users\argj\AppData\Local\Continuum\anaconda2\envs\GDAL2
TEST                  *  C:\Users\argj\AppData\Local\Continuum\anaconda2\envs\TEST
root                     C:\Users\argj\AppData\Local\Continuum\anaconda2
```
```
(TEST) C:\Users\argj>conda list gdal
# packages in environment at C:\Users\argj\AppData\Local\Continuum\anaconda2\envs\TEST:
#
gdal                      2.2.2                py27_vc9_0  [vc9]  conda-forge
libgdal                   2.2.2                     vc9_4  [vc9]  conda-forge
```

```
(TEST) C:\Users\argj>python -c "from osgeo import gdal"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\argj\AppData\Local\Continuum\anaconda2\envs\TEST\lib\site-packages\osgeo\__init__.py", line 25, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\argj\AppData\Local\Continuum\anaconda2\envs\TEST\lib\site-packages\osgeo\__init__.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: %1 er ikke et gyldig Win32-program.
```

In my root environment I get this result which is as expected:

```
(root) C:\Users\argj>conda list gdal
# packages in environment at C:\Users\argj\AppData\Local\Continuum\anaconda2:
#
GDAL                      2.2.2                     <pip>
libgdal                   2.2.2                     vc9_4  [vc9]  conda-forge
```

```
(root) C:\Users\argj>python -c "from osgeo import gdal; ds=gdal.Open(r'e:\temp\L2A_T32VPM_20170811T104021_B02_10m.jp2'); print ds.GetGeoTransform()"
(600000.0, 10.0, 0.0, 6700020.0, 0.0, -10.0)
```

My test jp2 file is 101 MB. How can I upload it so you can test it?

Many thanks for your respons!

**Comment by ocefpaf** [comment]
> My test jp2 file is 101 MB. How can I upload it so you can test it?

That won't do. We need a simpler one. I'll see if I can make one.

> In my root environment I get this result which is as expected:

It is possible that the driver is working on Linux and not on Windows.
I'll try to add a test for it once I create the file.

**Comment by akgjertsen** [comment]
It seems the issue not only has to do with failing jp2 driver. I tested this today on a tif file:

```
(TEST) C:\Users\argj>python -c "from osgeo import gdal; ds=gdal.Open(r'e:\temp\test2.tif'); print ds.GetGeoTransform()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\argj\AppData\Local\Continuum\anaconda2\envs\TEST\lib\site-packages\osgeo\__init__.py", line 25, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\argj\AppData\Local\Continuum\anaconda2\envs\TEST\lib\site-packages\osgeo\__init__.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: Den angitte modulen ble ikke funnet. 
```

And then the same on my root environment:

```
(root) C:\Users\argj>python -c "from osgeo import gdal; ds=gdal.Open(r'e:\temp\test2.tif'); print ds.GetGeoTransform()"
(635440.0, 10.0, 0.0, 6615570.0, 0.0, -10.0)
```

Could it be that some paths are missing/set wrong? It seems it cannot find a module named **_gdal.**

**Comment by ocefpaf** [comment]
Closing this as stale. I'm happy to re-open and work on a test if someone can provide a simple `jp2` file for the test.

**Comment by stephendb** [comment]
The jp2 driver is definitely still not present. jp2 is primarily used to store extremely large satellite image files, smallest ones are over 70MB so asking for a simple jp2 is sort of out of the question. However, you can create a fake jp2 file and will encounter the problem that most of us are having:
`import gdal`
`gdal.Open("stratmap18-nc-cir-6in-caparea-mclennan_3097422a1_20180124.jp2")`
`ERROR 4: `stratmap18-nc-cir-6in-caparea-mclennan_3097422a1_20180124.jp2' not recognized as a supported file format.`

Create a file `junk.jp2` and try to read you get the same error. The jp2 driver is missing.

**Comment by gillins** [comment]
Do you get the result below when running `gdalinfo --formats`? Seems the `JP2OpenJpeg` driver does actually read some of the file to determine if is is valid (https://github.com/OSGeo/gdal/blob/master/gdal/frmts/openjpeg/openjpegdataset.cpp#L1605) so you actually need a genuine jpeg2000 file for it to work.

Which OS are you on?

```
$ gdalinfo --formats | grep -i jp2
  JP2OpenJPEG -raster,vector- (rwv): JPEG-2000 driver based on OpenJPEG library
```

**Comment by stephendb** [comment]
Win10 x64
For reference, GDAL 3.0.1 wheels installed from https://www.lfd.uci.edu/~gohlke/pythonlibs/ includes JP2OpenJpeg and the gdal Open command works just fine on any of the jp2 files I've tested. It seems the conda installation specifically is missing drivers.

All of my machines have OSGeo4W installed separately so gdalinfo of course shows that the driver is installed. I don't have a machine with only the conda install to see if gdalinfo shows the drivers installed. 

I noticed the conda install was borked when I tried to install gdal through conda on a co-workers machine that was missing either a pip/wheel install of gdal or OSGeo4W both of which have the jp2 driver.

**Comment by gillins** [comment]
I think there may be a conflict between OSGeo4W and conda-forge. We specifically test for `JP2OpenJPEG` during the test phase of the build (see https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/run_test.py#L12). 

What error are you getting if you don't install pip etc?

**Comment by stephendb** [comment]
Feel like we're going in circles on this one.

Win10 x64
Fresh install (NO OSGeo4W or pip version installed or anything else for that matter, fresh machine)

`conda install gdal`
`python`
>>> import gdal
>>> gdal.Open("stratmap18-nc-cir-6in-caparea-mclennan_3097422a1_20180124.jp2")
>>> ERROR 4: stratmap18-nc-cir-6in-caparea-mclennan_3097422a1_20180124.jp2 not recognized as a supported file format.

I was only talking about OSGeo4W and the pip/wheel install because unlike the conda version those work. I was also verifying that there is nothing wrong with the file in question as it works just fine with OSGeo4W/pip/wheel.

I posted here because it's been frustrating not being able to use the conda install on any new machines I setup because the drivers don't work or are missing or something.

**Comment by gillins** [comment]
Works for me on Win10. Can you try installing into a new environment?:
```
conda create -n testgdal gdal
conda activate testgdal
```
This is the recommended approach since `gdal` needs a few things set up before it will run properly.

If you are still having trouble, send us the output of `conda list`.
