### ISSUE TITLE
Build gdal with external geotiff to avoid seg-faults

### ISSUE THREAD

**Issue by aashish24** [conda-forge/gdal-feedstock#187]
Currently it uses internal geotiff which is not mangled.

**Comment by gillins** [comment]
Good point.  I'll look at getting a geotiff recipe in conda-forge this week.

**Comment by aashish24** [comment]
thanks @gillins I have a patch if you would like me to push it. Looks like we will need to add geotiff to conda-forge as well.

**Comment by gillins** [comment]
>  Looks like we will need to add geotiff to conda-forge as well.

Yes it's been something that has been missing for a while. I've made a start here: https://github.com/gillins/staged-recipes/tree/geotiff/recipes/geotiff. I'll look at getting Windows building tomorrow, then add a PR. Let me know if you have any comments.

**Comment by gillins** [comment]
Fixed by https://github.com/conda-forge/libgdal-feedstock/pull/20 and https://github.com/conda-forge/libgdal-feedstock/pull/21

**Comment by aashish24** [comment]
thanks @gillins I will give it a try and let you know if I run into any issue thanks a bunch!
