### ISSUE TITLE
libxerces-c-3.1.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Liamdelee** [conda-forge/gdal-feedstock#190]
hi there
 i am pritty new to gdal and stuff and i got it u and running on an amazon ec2 instance but now i am porting it to an amazon elastic map reduce and i got miniconda installed and working with python2.7 got matplotlib installed and is importing without any erros but now i am installing gdal and this give me this wierd error: 
libxerces-c-3.1.so: cannot open shared object file: No such file or directory
where i have no clue about what it is and how i can solve it.
i hope you ppl can help me out many thanks

**Comment by ocefpaf** [comment]
First take a look at: https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

And we are going to need more details. Which version of `gdal`? How you installed it? Can you try a clean env and report if you still see the error?

**Comment by Liamdelee** [comment]
thanks for your fast answer,

i am running gdal 2.2.2 the latest you get with conda install gdal on python 2.7.
installed it using conda install gdal after i did conda config --add channels conda-forge
this is a full clean env for the second time so i don't think this is where the problem lays.

**Comment by Liamdelee** [comment]
okay i just found out that it did install xerces-c 3.2.0 but i have no idea how to downgrade that to 3.1.4
can you help me out with that?

**Comment by Liamdelee** [comment]
fixed the problem with doing: conda install xerces-c
