### ISSUE TITLE
Need a version that doesn't depend on hdf5_1.10.x

### ISSUE THREAD

**Issue by michaelaye** [conda-forge/gdal-feedstock#195]
Because of a bug in hdf5 1.10 (multiple parallel reads can fail), I need a version of gdal that does not hard-depend on hdf5 v1.10 but would work with hdf5 v1.8.x

Currently, importing gdal fails, after downgrading hdf5 while disregarding the dependencies (which I need to do, because the chain of dependencies leads back to a broken gdal regarding poppler versions):

```python
ImportError: dlopen(/Users/klay6683/miniconda3/envs/stable/lib/python3.6/site-packages/osgeo/_gdal.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libhdf5.101.dylib
  Referenced from: /Users/klay6683/miniconda3/envs/stable/lib/libgdal.20.dylib
  Reason: image not found
```

Would that be possible, please?

Working on macOS 10.12.6 and Python 3.6.

**Comment by Juanlu001** [comment]
I think this should be reported in libgdal instead: https://github.com/conda-forge/libgdal-feedstock/blob/b929c5b59cecac01d667513958808880d175294d/recipe/meta.yaml#L38

**Comment by ocefpaf** [comment]
> I need a version of gdal that does not hard-depend on hdf5 v1.10 but would work with hdf5 v1.8.x

We cannot handle personal requests that put a strain on our volunteers maintainers.
I would gladly review a PR that creates a variant with another `hdf5` though.
