### ISSUE TITLE
Import gdal gives error anaconda

### ISSUE THREAD

**Issue by abhilam** [conda-forge/gdal-feedstock#197]
I am trying to install gdal 2.2.2 on my anaconda. Eventhough it successfully installed but while importing as import gdal i am getting 

ImportError:libpoppler.so.71: cannot open shared object file: No such file or directory. 

Any help would be highly appreciated. 

Thank you.
Abhi

**Comment by ocefpaf** [comment]
Please read [this first](https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels).

Also, there is not enough information in your message to diagnose the issue. We need to know the platform and the commands you used to install `gdal`. Last but not least, latest version of `gdal` is `2.2.3`, and we do have LTS for `gdal 2.1.4`, but there is no support for `2.2.2`
