### ISSUE TITLE
GDAL 2.2.3 import error

### ISSUE THREAD

**Issue by abhilam** [conda-forge/gdal-feedstock#198]
I am running Ubuntu 16.04 with anaconda spyder 3.2.6.
I am trying to install GDAL 2.2.3 using 
python setup.py build
python setup.py install

terminal clearly said it is installed. but whenever i try to import gdal in spyder, i am getting error of 

ImportError: /home/abhishes/anaconda2/lib/python2.7/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN6kmldom15SerializePrettyB5cxx11ERKN5boost13intrusive_ptrINS_7ElementEEE

Currently, I do have libgdal2.2.2 installed

Thank you in advance.

Abhi

**Comment by ocefpaf** [comment]
This feedstock provides a binary for `conda` you should not use this to install it from source.

**Comment by abhilam** [comment]
Hi, thanks for your prompt response. could you please direct me how to use feedstock ?
Thank you

**Comment by ocefpaf** [comment]
What are you trying to do? If you are a conda used and want to install `gdal` you need to:

```shell
conda install -c conda-forge gdal=2.2.3
```

if you want to rebuild it for conda than I suggest you stat by reading about conda-build and conda-forge docs.

**Comment by abhilam** [comment]
I have tried as you suggested but doing so, this is the error I am getting. 

ImportError:libkea.so.1.4: cannot open shared object file: No such file or directory

Thank you.

**Comment by ocefpaf** [comment]
Please read https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

Here is a minimal example that should work there:

```shell
conda create --name TEST -c conda-forge gdal=2.2.3 python=3.6 --yes
source activate TEST
python -c 'import gdal; print(dir(gdal))'
```

**Comment by abhilam** [comment]
HI,
Thank you so much, your workaround solution creating environment worked. 
Now it could be a stupid question to ask but having newer in python, could you please suggest how to activate this environment in spyder python GUI. 

Thanks
