### ISSUE TITLE
Bit Length Overflow debug Messages

### ISSUE THREAD

**Issue by broxtopd** [conda-forge/gdal-feedstock#199]
Hi,

I have installed gdal with python2.7 and python 3.4 in Anaconda.  I have noticed that anytime I am working with compressed files using gdal, I get a whole bunch of debug messages (see below) which don't seem to affect the behavior, other than taking a while to print to screen and making it difficult to track progress.  These messages occur whether I am using the utility programs (e.g. gdal_translate) or using the python bindings.  For other GDAL installations, I do not receive these messages.  I believe this has to do with how GDAL is compiled (see http://osgeo-org.1560.x6.nabble.com/gdal-dev-bit-length-overflow-in-deflate-compress-td3742322.html).  Is it possible to prevent these messages from occurring in Anaconda python?

Sample output:

bit length overflow
code 14 bits 7->6
code 0 bits 5->6

bit length overflow
code 4 bits 6->7

bit length overflow
code 4 bits 6->7

bit length overflow
code 12 bits 6->7

bit length overflow
code 14 bits 6->7

bit length overflow
code 13 bits 6->7

bit length overflow
code 14 bits 6->7

bit length overflow
code 11 bits 6->7

bit length overflow
code 12 bits 6->7

bit length overflow
code 13 bits 6->7

bit length overflow
code 13 bits 6->7

bit length overflow
code 13 bits 6->7

bit length overflow
code 6 bits 6->7

**Comment by gillins** [comment]
Just need to check: are you using conda-forge `gdal` or Anaconda `gdal`? Can you post a link to one of the problem files?

**Comment by broxtopd** [comment]
Hi,

I believe that I am using Anaconda gdal.  Specifically, the package info
that I am currently looking at is (using the 'conda list' command):
gdal                      2.1.0                    py34_0
The only package that seems to match (using 'conda info gdal') is:
gdal 2.1.0 py34_0
-----------------
file name   : gdal-2.1.0-py34_0.tar.bz2
name        : gdal
version     : 2.1.0
build number: 0
build string: py34_0
channel     : defaults
size        : 543 KB
date        : 2016-07-21
fn          : gdal-2.1.0-py34_0.tar.bz2
license     : MIT
md5         : b9dd683c8d7b7e2883492cd58803de0a
priority    : 0
schannel    : defaults
url         :
https://repo.continuum.io/pkgs/free/win-64/gdal-2.1.0-py34_0.tar.bz2
dependencies:
    libgdal 2.1.0
    numpy
    python 3.4*


Here is a link to an example file where I get these messages:
https://www.dropbox.com/s/mchfr1p1ygjtpzn/Hillshade.tif?dl=0

You should be able to see the messages if you type:
gdal_translate -co COMPRESS=DEFLATE Hillshade.tif Hillshade2.tif

Patrick Broxton
Researcher
Arizona Remote Sensing Center
School of Natural Resources and the Environment

ENR2 Bldg. N407
1064 E. Lowell Street
The University of Arizona
Tucson, AZ  85721

**Comment by gillins** [comment]
This is the repository for the `conda-forge` `gdal` package. Report problems with the Anaconda packages here: https://github.com/ContinuumIO/anaconda-recipes.

BTW I tested your file with `conda-forge` `gdal` on Windows and it doesn't print the messages - so you may want to start using `conda-forge` as an interim (or permanent 😄) solution.
