### ISSUE TITLE
gdal utils report .../bin/../lib/libuuid.so.1: no version information available (required by .../bin/../lib/libdapserver.so.7)

### ISSUE THREAD

**Issue by akrherz** [conda-forge/gdal-feedstock#200]
Sorry that I am likely filing this issue in the wrong place, but my current conda-forge environment is emitting this warning whenever I run gdal utils
```
$ gdalinfo 
gdalinfo: /opt/miniconda2/bin/../lib/libuuid.so.1: no version information available (required by /opt/miniconda2/bin/../lib/libdapserver.so.7)
```
My root env is currently up2date with `conda update --all`, but I do notice some packages are old, for example `libdap4 == 3.18.3 2  conda-forge`.  If I attempt to update `libdap4`, I get 
```
$ conda update libdap4
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /opt/miniconda2:

The following packages will be UPDATED:

    libdap4: 3.18.3-2     conda-forge --> 3.19.2-1             conda-forge
    libpq:   9.6.3-0      conda-forge --> 9.6.6-h4e02ad2_0                

The following packages will be DOWNGRADED:

    gdal:    2.2.3-py27_0 conda-forge --> 2.2.2-py27hae9aa10_1            
    libgdal: 2.2.3-3      conda-forge --> 2.2.2-h804cdde_1   
```

So perhaps the libdap4 build needs bumped or maybe current gdal needs to require this newer dap4 ? I wish I was more help here.

**Comment by ocefpaf** [comment]
> Sorry that I am likely filing this issue in the wrong place

Nope, here is fine.

> My root env is currently up2date with `conda update --all`, but I do notice some packages are old, for example `libdap4 == 3.18.3 2  conda-forge`.  If I attempt to update `libdap4`, I get 

In my experience installing packages in the `root` env and using `update --all` is a recipe for disaster. It looks like you got a bad mix of `defaults` and `conda-forge` there. Please take a look at https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels and try installing things in a fresh env.

**Comment by akrherz** [comment]
Hi @ocefpaf , your support here is amazing.  Thank you.  Indeed, the follow emits no warnings
```
$ conda create -n gdal gdal
$ source activate gdal
$  gdalinfo
```
Yeah, I gotta move away from the `root` env.

**Comment by akrherz** [comment]
Eh, maybe there is an issue afoot here, I attempted to create my full install env as `prod` and am now reproducing this issue again.  Of note
```
$ ll /opt/miniconda2/envs/prod/bin/../lib/libuuid.so.1
lrwxrwxrwx 1 akrherz akrherz 16 Feb 28 14:15 /opt/miniconda2/envs/prod/bin/../lib/libuuid.so.1 -> libuuid.so.1.0.0
```
if `libuuid.so.1` is pointing to `libuuid.so.1.3.0`, things are OK.  At some point during my env install, that link got updated.  Any thoughts?

**Comment by akrherz** [comment]
investigating some more
```
$ conda package -w /opt/miniconda2/envs/prod/lib/libuuid.so.1
/opt/miniconda2/envs/prod/lib/libuuid.so.1          defaults::util-linux-2.21-0
/opt/miniconda2/envs/prod/lib/libuuid.so.1          conda-forge::libuuid-1.0.3-1
```
So I just manually updated the sym link for now to point at `libuuid.so.1.3.0`, think I should raise an issue with libuuid ?

**Comment by ocefpaf** [comment]
Please do. I'll take a closer look a this soon.

Also, please xref the with this issue.

**Comment by jakirkham** [comment]
FYI `util-linux` in `defaults` is just a build of `libuuid` with nothing else and hasn't been actively maintained AFAICT (first and last build was last year). The best plan is probably to switch over to our `libuuid`, which is maintained. Other than our `libuuid` being newer, it is a drop in replacement for `defaults` copy of `util-linux`. This should hopefully avoid file collisions, which likely gave rise to this issue.
