### ISSUE TITLE
GDAL linking error with HDF5

### ISSUE THREAD

**Issue by djhoese** [conda-forge/gdal-feedstock#209]
I haven't noticed anything updated on conda-forge's side recently that would cause this, but I'm going to put it here assuming it can be solved by the related parties. The related travis job is here: https://travis-ci.org/pytroll/satpy/jobs/398260457

And the relevant error:

```
  File "/home/travis/build/pytroll/satpy/satpy/writers/geotiff.py", line 30, in <module>
    from osgeo import gdal, osr
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/travis/miniconda/envs/test/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/travis/miniconda/envs/test/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libhdf5_cpp.so.102: cannot open shared object file: No such file or directory
```

I'll keep reviewing the installed packages to see if there is some defaults versus conda-forge channel issue.

**Comment by ocefpaf** [comment]
Everything that relies on `gdal` is broken at the moment b/c of the bump in the `hdf5` pin. I'm trying to rebuild the stack from the bottom up to fix this but if you can force a new `hdf5 1.10.2` there you can workaround it, if not you'll need to wait :-(

**Comment by djhoese** [comment]
Thanks for the info. Any idea how long it will take for all of the builds to catch up? End of the USA business day? This weekend? By SciPy :wink: ?

**Comment by ocefpaf** [comment]
Aiming for the weekend and hopefully not by SciPy :stuck_out_tongue_winking_eye:

**Comment by djhoese** [comment]
Is there a certain package I can watch build to know when this is complete...if I'm impatient enough?

**Comment by snowman2** [comment]
Everything worked for me with the pin `kealib=1.4.7`.

**Comment by ocefpaf** [comment]
It should. That version was not built with `hdf5 1.10.2`.

**Comment by djhoese** [comment]
My tests seem to be passing now. Thanks @ocefpaf.
