### ISSUE TITLE
Link gdal to jpeg and zlib on Windows

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/gdal-feedstock#21]
@gillins:

> Under Windows GDAL cannot be build against an external zlib for some reason (there is no option to do this). jpeg isn't available as a DLL under Windows, and the provided .lib is built for use in a .exe rather than a .dll so it won't even link to GDAL (another conda-forge project??)

- [X] [`jpeg`](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/bld.bat#L56-L58)
- [ ] `zlib`

**Comment by gillins** [comment]
Fixed in jpeg-feedstock

**Comment by ocefpaf** [comment]
Thanks @gillins!
