### ISSUE TITLE
libgdal marked as "broken" on anaconda.org

### ISSUE THREAD

**Issue by mrterry** [conda-forge/gdal-feedstock#212]
Yesterday a whole bunch of libgdal builds were marked as "broken" on anaconda.org. This broke a whole bunch of environments that where otherwise fine. Was this an intentional change?

Historically libgdal has had problems where it does not entirely specify its dependencies, resulting in linker errors when the exact right versions of hdf5/kealib/etc aren't found.  Should I expect libgdal to be on the straight an narrow from now on?

PS I manage py2 & py3 envs on mac & linux that use gdal and can help pin down dependencies if that is of use.

**Comment by ocefpaf** [comment]
I recommend you to make a looser pin for `libgdal` b/c every time we rebuild it with new dependencies the old build number is no longer reliable. (Unfortunately `conda` does not always get the latest build number, forcing us to move them to "broken.")

I use `libgdal 2.2.*` everywhere and things work fine. Note that, even though we have `libgdal 2.3.1` we are not building `rasterio` and `fiona` with it yet.

**Comment by mrterry** [comment]
Am I understanding you correctly in that you're clobbering build numbers?  That makes it very difficult to have reproducible environments.

**Comment by ocefpaf** [comment]
> Am I understanding you correctly in that you're clobbering build numbers? That makes it very difficult to have reproducible environments.

Not at all. We move them to the `broken` label exactly to ensure reproducibility when it is needed. What I said is that, for user envs we recommend the use of a looser pin, like `libgdal 2.2.*`, and let `conda` find the right dependencies for you.

**Comment by mrterry** [comment]
My apologies for all the questions. I appreciate the wok of conda-forge and its maintainers. I'm just trying to figure out things work so that I'm not fighting you in my day job.

 How does adding the `broken` label ensure reproducibility? Builds labeled as `broken` are invisible to conda (at least on mac), which makes previously working env files turn into `UnsatisfiableError`s. (You can add the `conda-forge/label/broken` channel, but that is a little scary).

Also, in my experience, simply adding `libgdal` as a dependency would often result in unworking environments. These are often in old Python versions (it was a big problem with 2.7.7, but still with 2.7.13 and 3.6). There always existed a set of gdal/geos/kealib/&friends combination that worked, conda didn't appear to have the necessary information to find it. When I found a set of versions that worked, I'd pin everything down & move on. Perhaps my paranoia should be restricted to working with very old builds of libgdal, but it is still there.

**Comment by ocefpaf** [comment]
> How does adding the broken label ensure reproducibility? Builds labeled as broken are invisible to conda (at least on mac), which makes previously working env files turn into UnsatisfiableErrors. (You can add the conda-forge/label/broken channel, but that is a little scary).

You'll need to specifically ask for those b/c, as the label says, they are not ensure to work unless you know what you are doing. Again, see my recommendation above to get the correct set of dependencies.

If you really need an old build note that a `label` behaves like a channel in `conda` and you can get a package from there in many ways, one is:

```
conda create --name TEST python=3.6 conda-forge/label/broken::libgdal=2.3.0
````

> Also, in my experience, simply adding libgdal as a dependency would often result in unworking environments.

Again, you should pin to a minor version number like `2.2.*`, I use that on my day job without any issues.

> There always existed a set of gdal/geos/kealib/&friends combination that worked, conda didn't appear to have the necessary information to find it. When I found a set of versions that worked, I'd pin everything down & move on. Perhaps my paranoia should be restricted to working with very old builds of libgdal, but it is still there.

Extremely specific cases are really hard to get "right" as we update dependencies. You are better off caching those packages locally or, better yet, fixing your env to work with the latest versions of the dependencies. I'm pretty sure looser pins for the versions will get you there.
