### ISSUE TITLE
Are jpeg12 and ECW support possible?

### ISSUE THREAD

**Issue by jacobadams-cc** [conda-forge/gdal-feedstock#217]
Issue:

Is there any possibility of including jpeg12 and ECW-read support in the conda-forge gdal feedstock? I've looked in the issue tracker and haven't seen either of these mentioned previously.

I'm running into issues with a jpeg-compeessed tiff from ArcGIS that is set to nbits=12, which seems to indicate conda-forge's gdal doesn't have jpeg12 support enabled as outlined in [https://trac.osgeo.org/gdal/wiki/TIFF12BitJPEG](url). Is it possible to enable this, or is there a history I've missed explaining why it's not?

While we're here, is there any chance of adding ECW read support as well? I realize this may not be feasible with all the licensing stuff.

My workaround for both of these is to use the gdal_translate.exe binary from a QGIS install to translate these files to a format supported by the conda-forge installation and then work from there. This still works, but it'd be nice to have direct support.

Thanks for maintaining this feedstock. Running an up-to-date version of gdal via conda-forge is so, so much easier than the other methods out there.
<br/>

(Omitting all the environment info as this is just a feature request. I just updated gdal to 2.3.1 from the conda-forge channel in Anaconda Navigator to confirm the behavior exists in the current build).

**Comment by jacobadams-cc** [comment]
I'll take a stab at a PR; I've identified the relevant statements in the libgdal meta/build files.

Being new to conda development, do I need to test changes locally via conda build before submitting a PR, or is that what the conda-forge CI tools are intended to do? I can set up a windows build environment without that much headache, but osx and linux will take a while longer.

**Comment by ocefpaf** [comment]
> do I need to test changes locally via conda build before submitting a PR, 

You don't have to do it but it is easier to fix errors that way.

>  I can set up a windows build environment without that much headache, but osx and linux will take a while longer.

OS X is usually harder but Linux you can use our docker image, even from Windows:

https://conda-forge.org/docs/testing.html#docker-tests

**Comment by kevalshah90** [comment]
I am experiencing incompatibility issues with jpeg installing gdal library. I have tried pip and conda forge installations seperately for both the libraries, however, it seems like there is no jpeg support. 
 
![screen shot 2018-08-26 at 21 25 02](https://user-images.githubusercontent.com/4792353/44640528-0848ef00-a977-11e8-8308-c9535395e2cf.png)

**Comment by ocefpaf** [comment]
You are probably hitting this conda issue: https://github.com/conda/conda/issues/7656

Try to remove `defaults` from your configuration and you can at least debug the output rather than having a broken environment.

**Comment by mrpgraae** [comment]
@jacobadams-cc Are you still working on this, I am also in the need of ECW support.

**Comment by kmuehlbauer** [comment]
@conda-forge/gdal @conda-forge/libgdal 

While adapting the patches for v2.4.0 (#254) I found that we proactively disable jpeg12 support. It seems it was disabled because of problems with windows. @gillins Do you remember what was the main reason for that and is this still an issue?

Otherwise we could try re-enabling jpeg12 support after v2.4.0 is merged.

**Comment by msarahan** [comment]
One thing to keep in mind is that the deep learning community is pushing to have jpeg-turbo be more standard or at least an option. That conflicts with jpeg 9 because the library babes are the same. Using the internal sources may avoid a conflict there if these functions are built directly into libgdal rather than a jpeg so. I don't see strong reasons to avoid it, since jpeg is not a security sensitive library in general, and thus doesn't benefit from being able to slide in new dynamic libs as much.

**Comment by gillins** [comment]
`libecw` requires a [commercial license](https://www.hexagongeospatial.com/technical-documents/erdas-ecw-jp2-sdk-user-guide) so we cannot use it. 

As for jpeg12, we have been [advised](https://github.com/conda-forge/gdal-feedstock/pull/255#issuecomment-451235642) use external `libjpeg`, `libtiff` etc, but `gdal` currently has [no way](https://github.com/conda-forge/libtiff-feedstock/pull/37#issuecomment-451727931) of linking to them in 12 bit mode. I've also just [discovered](https://github.com/conda-forge/libtiff-feedstock/pull/37#issuecomment-454624408) that `libjpeg` no longer compiles in 12 bit mode anyway. May revisit when support improved upstream.

**Comment by wkrill** [comment]
If anyone is here looking for a GDAL installation with ECW support, there is a Docker recipe here: https://github.com/DHI-GRAS/ecw2tiff/blob/main/Dockerfile
