### ISSUE TITLE
gdalwarp missing libjson library...

### ISSUE THREAD

**Issue by mhearne-usgs** [conda-forge/gdal-feedstock#23]
Mac OS 10.10.5
conda 4.0.5
conda create --name py3exp python=3 -y
source activate py3exp

Then I run the following shell script:

```shell
#!/bin/sh

echo "1 2 3 4\n5 6 7 8\n9 10 11 12\n13 14 15 16" > grid.asc
echo "ncols 4\nnrows 4\nxllcenter -70.0\nyllcenter -19.0\ncellsize 5\nodata_value -9999\n" > grid.hdr
proj4="+y_0=2400761.714982585 +lat_ts=-19.6097 +a=6378137.0 +proj=merc +units=m +b=6356752.3142 +lat_0=-19.6097 +x_0=-0.0 +lon_0=-70.7691"
gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt
```

and I get the following error:

dyld: Library not loaded: /usr/local/lib/libjson-c.2.dylib
  Referenced from: /Users/mhearne/anaconda/envs/py3exp/bin/gdalwarp
  Reason: image not found
testwarp.sh: line 6: 19723 Trace/BPT trap: 5       gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt

**Comment by ocefpaf** [comment]
@mhearne-usgs I am afraid we are opening a can or worms here (meaning more missing dependencies that are masked due to the Travis-CI OS X image we are using.). I will ping you as soon as the new binaries are in the channel for further tests.  Thanks for reporting this.

**Comment by ocefpaf** [comment]
@mhearne-usgs the new binaries are in the [channel](http://anaconda.org/conda-forge/gdal/files). Let us know if that solves the problem for you.

**Comment by mhearne-usgs** [comment]
conda create --name py3exp python=3
conda install -c conda-forge gdal

which gdalwarp
/Users/mhearne/anaconda/envs/py3exp/bin/gdalwarp

And here's the output from the important line of my test script:

gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt
dyld: Library not loaded: /usr/local/lib/libjson-c.2.dylib
  Referenced from: /Users/mhearne/anaconda/envs/py3exp/bin/gdalwarp
  Reason: image not found
Trace/BPT trap: 5

**Comment by ocefpaf** [comment]
Can you send me the output of `conda list` so I can see what release you got there.

**Comment by ocefpaf** [comment]
Try this too:

```shell
conda create --name py3exp --channel conda-forge python=3 gdal==1.11.4
source activate py3exp
```

and then run your script. (I maintain `gdal` 1.11.4. If my solution work I will port that to `gdal` 2)

**Comment by mhearne-usgs** [comment]
Results of conda list, trying second suggestion now:

# packages in environment at /Users/mhearne/anaconda/envs/py3exp:
#
curl                      7.45.0                        0    defaults
gdal                      2.0.2               np110py35_1    conda-forge
geos                      3.4.2                         1    conda-forge
hdf4                      4.2.11                        0    defaults
hdf5                      1.8.15.1                      2    defaults
jbig                      2.1                           0    defaults
jpeg                      8d                            1    defaults
kealib                    1.4.5                         0    defaults
krb5                      1.13.2                        0    defaults
libnetcdf                 4.3.3.1                       3    defaults
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         1    defaults
mkl                       11.3.1                        0    defaults
numpy                     1.10.4                   py35_0    defaults
openjpeg                  2.1.0                         1    conda-forge
openssl                   1.0.2g                        0    defaults
pip                       8.1.1                    py35_1    defaults
proj.4                    4.9.1                         2    conda-forge
python                    3.5.1                         0    defaults
readline                  6.2                           2    defaults
setuptools                20.3                     py35_0    defaults
sqlite                    3.9.2                         0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py35_0    defaults
xerces-c                  3.1.2                         0    defaults
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         0    defaults

**Comment by ocefpaf** [comment]
As I suspected you had gdal 2 installed. Sorry for not letting you know that first. As soon as we can confirm that my solution works I will port that to the gdal 2 branch.

**Comment by mhearne-usgs** [comment]
libjson bug is gone, but now I get:

gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt

ERROR 4: `grid.asc' not recognised as a supported file format.

**Comment by ocefpaf** [comment]
I got that when adapting your script. I modified it to look like this and
it worked:

https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/run_test.sh

If you google that error you'll see some other issues related, but I am not
a gdal expert to comment. Package wise it looks that the issue is resolved.
I will send this to the gdal2 soon.
Em 03/04/2016 14:49, "Mike Hearne" <notifications@github.com> escreveu:

**Comment by mhearne-usgs** [comment]
I am now trying to merge the issues I've had with gdal, fiona, and hdf into a single install script.  What I have below fails on the gdalwarp test.  I'm willing to bet that there is a workaround, I just can't figure out what it is...

#!/bin/sh

#try to install everything I need
source activate root
conda remove --name shake --all -y
conda create --name shake --yes --channel conda-forge python=3 h5py fiona -y
source activate shake
conda uninstall libnetcdf -y
#conda install -y gdal==1.11.4
conda install hdf5==1.8.16 -y
conda install rasterio -y --no-deps
python -c "import h5py"

rm grid.asc
rm grid.hdr
rm grid.flt

#run the gdalwarp test
# From @mhearne-usgs. See https://github.com/conda-forge/gdal-feedstock/issues/23#issue-144997326
echo "1 2 3 4" > grid.asc
echo "5 6 7 8" >> grid.asc
echo "9 10 11 12" >> grid.asc
echo "13 14 15 16" >> grid.asc

echo "ncols 4" > grid.hdr
echo "nrows 4" >> grid.hdr
echo "xllcenter -70.0" >> grid.hdr
echo "yllcenter -19.0" >> grid.hdr
echo "cellsize 5" >> grid.hdr
echo "odata_value -9999" >> grid.hdr

proj4="+y_0=2400761.714982585 +lat_ts=-19.6097 +a=6378137.0 +proj=merc +units=m +b=6356752.3142 +lat_0=-19.6097 +x_0=-0.0 +lon_0=-70.7691"

gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt

**Comment by ocefpaf** [comment]
This worked for me:

```shell
#!/bin/sh

conda create --name TEST --yes --channel conda-forge python=3 \
                               h5py \
                               fiona \
                               rasterio \
                               gdal=1.11.4=np110py35_0 \

source activate TEST
python -c "import h5py"

# Run the gdalwarp test.
echo "1 2 3 4" > grid.asc
echo "5 6 7 8" >> grid.asc
echo "9 10 11 12" >> grid.asc
echo "13 14 15 16" >> grid.asc

echo "ncols 4" > grid.hdr
echo "nrows 4" >> grid.hdr
echo "xllcenter -70.0" >> grid.hdr
echo "yllcenter -19.0" >> grid.hdr
echo "cellsize 5" >> grid.hdr
echo "odata_value -9999" >> grid.hdr

proj4="+y_0=2400761.714982585 +lat_ts=-19.6097 +a=6378137.0 +proj=merc +units=m +b=6356752.3142 +lat_0=-19.6097 +x_0=-0.0 +lon_0=-70.7691"

gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt
```

Note that I am pinning gdal to a specific release (before the new `hdf5` was introduced). The real solution is to get our netCDF out there ASAP, but we are low on resources right...

PS: If you want another Python or numpy version change the string `np110py35_0`, but always keep the `0` as that is the one compiled against the old `hdf5`.

**Comment by ocefpaf** [comment]
BTW maybe you made that script just to test this issue, but if you ever have the need to create an `env` inside a script take a look at [conda-execute](https://github.com/pelson/conda-execute).

**Comment by mhearne-usgs** [comment]
I ran the below modified version of your script, and got the following errors:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mhearne/anaconda/envs/TEST/lib/python3.5/site-packages/h5py/__init__.py", line 24, in <module>
    from . import _errors
ImportError: dlopen(/Users/mhearne/anaconda/envs/TEST/lib/python3.5/site-packages/h5py/_errors.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libhdf5.10.dylib
  Referenced from: /Users/mhearne/anaconda/envs/TEST/lib/python3.5/site-packages/h5py/_errors.cpython-35m-darwin.so
  Reason: Incompatible library version: _errors.cpython-35m-darwin.so requires version 12.0.0 or later, but libhdf5.10.dylib provides version 11.0.0
dyld: Library not loaded: /usr/local/lib/libjson-c.2.dylib
  Referenced from: /Users/mhearne/anaconda/envs/TEST/bin/gdalwarp
  Reason: image not found
gdaltest2.sh: line 26: 63070 Trace/BPT trap: 5       gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt

#!/bin/sh

source activate root
conda remove --name TEST --all -y
conda create --name TEST --yes --channel conda-forge python=3 h5py fiona rasterio gdal=1.11.4=np110py35_0

source activate TEST
python -c "import h5py"

# Run the gdalwarp test.

echo "1 2 3 4" > grid.asc
echo "5 6 7 8" >> grid.asc
echo "9 10 11 12" >> grid.asc
echo "13 14 15 16" >> grid.asc

echo "ncols 4" > grid.hdr
echo "nrows 4" >> grid.hdr
echo "xllcenter -70.0" >> grid.hdr
echo "yllcenter -19.0" >> grid.hdr
echo "cellsize 5" >> grid.hdr
echo "odata_value -9999" >> grid.hdr

proj4="+y_0=2400761.714982585 +lat_ts=-19.6097 +a=6378137.0 +proj=merc +units=m +b=6356752.3142 +lat_0=-19.6097 +x_0=-0.0 +lon_0=-70.7691"

gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt

**Comment by ocefpaf** [comment]
Now we are between a rock and a hard place :smiley: 

On OS X you need the latest build, but the latest build will break due to `netcdf`. I am planning on fixing all the related builds to the old `hdf5` until we fix this.  Hold  on...

**Comment by mhearne-usgs** [comment]
Getting the gdal command line tools will ultimately be important, but the libraries (libgdal, h5py, fiona, etc.) are much more useful right now.  So, don't kill yourself trying to fix this particular issue quickly on my account.

**Comment by ocefpaf** [comment]
Don't worry. Most of the IOOS users (that I have to support) are interested into that stack. It is first priority to get that working to end the channel migration :wink:

**Comment by ocefpaf** [comment]
@mhearne-usgs I rebuilt everything using `hdf5 1.8.15.1` (compatible with the default channel's `libnetcdf`) and `gdal 1.11.4` to avoid issues when installing `fiona` together with other software that uses `gdal`. That should give you some stability as long as conda doesn't upgrade your `hdf5`, which you can downgrade manually in case it happens.

The only library I did not pin to the older `hdf5` was `h5py`. The reason for that is because the conda-forge team maintaining the new `hdf5` and `h5py` have a reason to use the latest version (that are not available in the default channel).

As soon as we build our own `libnetcdf` this problem will go (partly\*) away and you'll be free to upgrade to latest versions everywhere.

Now this should work:

```shell
#!/bin/sh

conda create --name TEST --yes --channel conda-forge python=3 \
                               h5py \
                               fiona \
                               rasterio \
                               gdal==1.11.4 \

source activate TEST
python -c "import h5py"

# Run the gdalwarp test.
echo "1 2 3 4" > grid.asc
echo "5 6 7 8" >> grid.asc
echo "9 10 11 12" >> grid.asc
echo "13 14 15 16" >> grid.asc

echo "ncols 4" > grid.hdr
echo "nrows 4" >> grid.hdr
echo "xllcenter -70.0" >> grid.hdr
echo "yllcenter -19.0" >> grid.hdr
echo "cellsize 5" >> grid.hdr
echo "odata_value -9999" >> grid.hdr

proj4="+y_0=2400761.714982585 +lat_ts=-19.6097 +a=6378137.0 +proj=merc +units=m +b=6356752.3142 +lat_0=-19.6097 +x_0=-0.0 +lon_0=-70.7691"

gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt
```

\* partially because `fiona` still depends on `gdal 1.11.4`. We won't be able to use `gdal 2` until a new `fiona` is released.

**Comment by mhearne-usgs** [comment]
@ocefpaf I went away from this for a while, but came back and tried the above script, and got the following errors:

dyld: Library not loaded: @rpath/libtiff.5.dylib
  Referenced from: /Users/mhearne/anaconda/envs/TEST/bin/gdalwarp
  Reason: Incompatible library version: gdalwarp requires version 8.0.0 or later, but libtiff.5.dylib provides version 7.0.0
./testme.sh: line 27: 80976 Trace/BPT trap: 5       gdalwarp -s_srs "+proj=latlong" -t_srs "$proj4" -of EHdr grid.asc grid.flt

**Comment by ocefpaf** [comment]
@mhearne-usgs a lot has changed since you've been gone :smile: 

We are re-building the `gdal` stack from the ground up and, hopefully, we will have a working version (for `Python 2.7 and 3.4`) tomorrow.

Python 3.5 is still on hold due to a `libzma` mismatch, but soon that will be solved by https://github.com/conda-forge/staged-recipes/pull/370
