### ISSUE TITLE
the latest gdal-2.3.1 is incompatible with the library libxml2.2.dylib . 

### ISSUE THREAD

**Issue by yinlu** [conda-forge/gdal-feedstock#230]
Issue:
I installed the latest gdal and libxml2, I got the following error:

gdalinfo:

dyld: Library not loaded: /usr/local/opt/libxml2/lib/libxml2.2.dylib
  Referenced from: /usr/local/bin/gdalinfo
  Reason: Incompatible library version: gdalinfo requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
Abort trap: 6

 I couldn't find older version might work with libxml2 version 10.0.0, neither I could find the libxml2 with libxml2.2.dylib==12.0.0.

How do I resolve this? 

Thanks.

Yin

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by yinlu** [comment]
I am using Mac Book Pro with OS 10.13.6.

**Comment by yinlu** [comment]
when I tried to install gdal==2.2.2, I got this error:

Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/3y/74lzbj5110lg75zd2vvpvpx40000gn/T/pip-install-IzwvZl/gdal/

**Comment by gillins** [comment]
It looks like you are installing `gdal` via `pip` which is likely to fail due to different libraries. What happens if you just use conda-forge?:
```
conda create -n mytest gdal
conda activate mytest
```

**Comment by ocefpaf** [comment]
Closing this b/c it is unrelated to conda-forge's gdal.
