### ISSUE TITLE
New environments fail on Windows with Python 2.7

### ISSUE THREAD

**Issue by djhoese** [conda-forge/gdal-feedstock#244]
This is a continuation of #241. The recipe for GDAL 2.3.2 was updated in #243 to look for `tiff.dll` coming from the new builds of the `libtiff` package (instead of `libtiff.dll`). If I recall correctly gdal no longer supports python 2 on Windows (found it: https://github.com/conda-forge/gdal-feedstock/issues/241#issuecomment-443463792). This means that any gdal build for Windows Python 2.7 is still looking for the "old" `libtiff.dll` but is automatically finding the newer libtiff builds with `tiff.dll`. Resulting in:

```
(appveyor_debug_27) C:\Users\User>python -c "from osgeo import gdal, osr"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\Anaconda3\envs\appveyor_debug_27\lib\site-packages\osgeo\__init__.py", line 25, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\User\Anaconda3\envs\appveyor_debug_27\lib\site-packages\osgeo\__init__.py", line 21, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified module could not be found.
```

I could be wrong but I don't think the gdal package is pinned to a specific version/build of libtiff. Would it be possible to do this? Would you be willing to accept a PR for a new build of gdal 2.2.4 with the `tiff.dll` fixes backported? Or with `libtiff` version hardcoded to something earlier than the `tiff.dll` change?

Otherwise, I think the only option (considering the life cycle of python 2.7) would be to require uses to install a specific build of gdal and/or libtiff.

Thoughts?

Side note: I can't seem to get python 3.6 on Windows to work on appveyor with a brand new environment but my Windows VM is working fine. For some reason it isn't picking up the new gdal build.

**Comment by ocefpaf** [comment]
> I could be wrong but I don't think the gdal package is pinned to a specific version/build of libtiff. 

That is probably the problem.

> Would you be willing to accept a PR for a new build of gdal 2.2.4 with the tiff.dll fixes backported? Or with libtiff version hardcoded to something earlier than the tiff.dll change?

Yes please :smile: 

(I was planning on doing that next week but if you can move this forward now that would be awesome.)

> Side note: I can't seem to get python 3.6 on Windows to work on appveyor with a brand new environment but my Windows VM is working fine. For some reason it isn't picking up the new gdal build.

It can be a temporary thing with the packages mirror.

**Comment by djhoese** [comment]
@ocefpaf Can I specify a specific build of libtiff in gdal's meta.yaml? Or should I backport the tiff.dll change?

**Comment by ocefpaf** [comment]
> @ocefpaf Can I specify a specific build of libtiff in gdal's meta.yaml? Or should I backport the tiff.dll change?

Backporting is the way to go. I should remove the other builds after that.

**Comment by djhoese** [comment]
@ocefpaf Since I don't know of any other way to contact you, do you have any other ideas for why a python 3.6 windows installation on appveyor isn't finding the new packages? I haven't tried forcing the exact build yet.

**Comment by ocefpaf** [comment]
> @ocefpaf Since I don't know of any other way to contact you, do you have any other ideas for why a python 3.6 windows installation on appveyor isn't finding the new packages? I haven't tried forcing the exact build yet.

That may be related to the new mirror. Ping @msarahan here.

**Comment by djhoese** [comment]
> PS: may people on gitter know already the reason. I'm in a workshop with limited attention to conda-forge at the moment.

Understood. You are being more accommodating that you need to be 😉 

Anyway, I found the issue, both cartopy and rasterio are also needed in my appveyor environment and are using older versions of geos/libgdal. It looks like what @dopplershift is working on in https://github.com/conda-forge/cartopy-feedstock/pull/56 will fix the cartopy incompatibility. I still need to look at any complications with rasterio updating to the new libgdal.

**Comment by dopplershift** [comment]
Cartopy will require figuring out how to pin older versions of GEOS and Proj4 only on Windows vc9, which @ocefpaf has been trying to do. I really hate legacy Python.

**Comment by ocefpaf** [comment]
Should be fixed by https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/160 and https://github.com/conda-forge/gdal-feedstock/pull/246

**Comment by ocefpaf** [comment]
I guess this was fixed in the PRs mentioned above. Closing the issue, please re-open if the problem persists.
