### ISSUE TITLE
Segmentation fault in python 3.6 environment with gdal 2.3.3

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/gdal-feedstock#261]
On the geopandas Travis CI, we recently started to see errors in one specific environment, created with https://github.com/geopandas/geopandas/blob/master/ci/travis/36-pd020.yaml (environment is created with `conda env create --file` with that file) 

It simply segfaults during pytest collection on Travis, and I can also reproduce it locally by creating that environment. Importing fiona or gdal first gives an error `ImportError: /home/joris/miniconda3/envs/test/lib/python3.6/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs`, and on a second import is gives a segmentation fault.

The conda list from recreating it locally is added below, the output of conda list on travis can be seen eg here: https://travis-ci.org/geopandas/geopandas/jobs/484650590. From that, everything seems fine (only mkl, numpy, scipy come from defaults, all the rest from conda-forge)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/joris/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                py36_1003    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              he56eebe_3    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5          py36h9745a5d_1001    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
codecov                   2.0.15                     py_1    conda-forge
coverage                  4.5.2           py36h14c3975_1000    conda-forge
cryptography              2.3.1           py36hb7f436b_1000    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
descartes                 1.1.0                      py_2    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fiona                     1.8.4           py36heb36068_1001    conda-forge
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.3.2            py36hb00a9d7_0    conda-forge
geographiclib             1.49                       py_0    conda-forge
geopy                     1.18.1                     py_0    conda-forge
geos                      3.6.2                hfc679d8_4    conda-forge
geotiff                   1.4.2             hfe6da40_1005    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
intel-openmp              2019.1                      144  
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
kealib                    1.4.10            hc069b17_1000    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.3.2                hc73897a_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.1             hc6a9f4b_1010    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libspatialindex           1.8.5             hf484d3e_1003    conda-forge
libspatialite             4.3.0a            h9968ff2_1023    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h9022e91_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
mapclassify               2.0.1                      py_0    conda-forge
matplotlib                1.5.3                    py36_9    conda-forge
mkl                       2019.1                      144  
more-itertools            4.3.0                 py36_1000    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.13.3           py36ha266831_3  
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
pandas                    0.20.2              np113py36_1    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pluggy                    0.8.1                      py_0    conda-forge
poppler                   0.67.0               hb55ee21_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
psycopg2                  2.7.6.1         py36hb7f436b_1000    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
py                        1.7.0                      py_0    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.5.1         py36h2944ce7_1006    conda-forge
pyqt                      5.6.0           py36h13b7fb3_1008    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytest                    4.1.1                 py36_1000    conda-forge
pytest-cov                2.6.1                      py_0    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
qt                        5.6.2                h50c60fd_8    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py36_1000    conda-forge
rtree                     0.8.3                 py36_1000    conda-forge
scipy                     1.2.0            py36h7c811a0_0  
setuptools                40.6.3                   py36_0    conda-forge
shapely                   1.6.4           py36h0c48222_1000    conda-forge
sip                       4.18.1          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlalchemy                1.2.16          py36h14c3975_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tornado                   5.1.1           py36h14c3975_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zstd                      1.3.3                         1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : test
    active env location : /home/joris/miniconda3/envs/test
            shell level : 2
       user config file : /home/joris/.condarc
 populated config files : /home/joris/.condarc
          conda version : 4.5.11
    conda-build version : 3.10.9
         python version : 3.5.5.final.0
       base environment : /home/joris/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/joris/miniconda3/pkgs
                          /home/joris/.conda/pkgs
       envs directories : /home/joris/miniconda3/envs
                          /home/joris/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.14.2 CPython/3.5.5 Linux/4.4.0-141-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by kmuehlbauer** [comment]
@jorisvandenbossche I doubt, that it is possible to get the environment running with matplotlib pinned to 1.5.3. The whole stack diverged to much. I'm sure we can't fix this, without immense effort. @ocefpaf might have a workaround for you problem, though.

**Comment by jorisvandenbossche** [comment]
Ah, didn't notice the old matplotlib pin. Thanks! 
Tried it locally, and indeed removing that pin resolves the issue (just removing the pin then installs gdal 2.4 instead of 2.3, but adding back a pin of `gdal=2.3` to keep testing that version still seems to work, as long as matplotlib >= 2).

So this seems to solve it (https://github.com/geopandas/geopandas/pull/903), but I would still have expected from conda to complain about not-satisfiable versions or something like that.

**Comment by mingwandroid** [comment]
The issue is that version incompatibilities often only happen in retrospect, even for software that tries to follow semver.  In particular any change to build settings or deps can easily cause this. 

So metadata does need curating, even old metadata baked into old packages. 

We do not have crystal balls

**Comment by jorisvandenbossche** [comment]
I can fully understand that! And thanks a lot for all the efforts on this!

**Comment by jorisvandenbossche** [comment]
OK, another case (trying to fix the CI of another package, contextily, see https://github.com/darribas/contextily/issues/56). Now without any pinnings to old packages, except that it is for python 3.5:

```
conda create -n TEST python=3.5 rasterio matplotlib pillow -c conda-forge
```

creates an environment with a segfaulting gdal:

```
(TEST2) joris@joris-XPS-13-9350:~/scipy/geo/contextily$ python
Python 3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/joris/miniconda3/envs/TEST2/lib/python3.5/site-packages/rasterio/__init__.py", line 23, in <module>
    from rasterio._base import gdal_version
ImportError: /home/joris/miniconda3/envs/TEST2/lib/python3.5/site-packages/rasterio/../../../libgdal.so.20: undefined symbol: _ZN11xercesc_3_211InputSource11setEncodingEPKt
>>> import rasterio
Segmentation fault (core dumped)
```

Any idea about which package I could pin at certain version to get rasterio / matplotlib combination working on python 3.5 ?

The full installed `conda list`:

<details>
<summary>Ouput of `conda list`</summary>

# packages in environment at /home/joris/miniconda3/envs/TEST2:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
asn1crypto                0.24.0                   py35_3    conda-forge
attrs                     18.2.0                     py_0    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
boto3                     1.9.86                     py_0    conda-forge
botocore                  1.12.86                    py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12           h80bd089_1005    conda-forge
certifi                   2018.8.24             py35_1001    conda-forge
cffi                      1.11.5           py35h5e8e0c9_1    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.3.1            py35hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                    py35_0    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
docutils                  0.14                     py35_1    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
geos                      3.7.0             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.56.2            had28632_1001    conda-forge
gst-plugins-base          1.12.5            h3865690_1000    conda-forge
gstreamer                 1.12.5            h0cc0488_1000    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.7                      py35_2    conda-forge
intel-openmp              2019.1                      144  
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            he7154bc_1002    conda-forge
kiwisolver                1.0.1            py35h2d50403_2    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.2.4               h9c39fcf_11    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libspatialite             4.3.0a            h06a27ec_1025    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h9022e91_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
matplotlib                2.2.3            py35h8e2386c_0    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.9                    py35_0    conda-forge
mkl_random                1.0.1                    py35_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.2           py35h1d66e8a_0  
numpy-base                1.15.2           py35h81de0dd_0  
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pillow                    5.3.0            py35hc736899_0    conda-forge
pip                       18.0                  py35_1001    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0            h2fc8fa2_1002    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                   py35_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyqt                      5.6.0            py35h8210e8a_7    conda-forge
pysocks                   1.6.8                    py35_2    conda-forge
python                    3.5.5                h5001a0f_2    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
rasterio                  1.0.7            py35h1b5fcde_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
s3transfer                0.1.13                   py35_1    conda-forge
setuptools                40.4.3                   py35_0    conda-forge
sip                       4.18.1           py35hfc679d8_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
snuggs                    1.4.1                      py_1    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tornado                   5.1.1            py35h470a237_0    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.23                     py35_1    conda-forge
wheel                     0.32.0                py35_1000    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
zstd                      1.3.3                         1    conda-forge

</details>

**Comment by ocefpaf** [comment]
> So this seems to solve it (geopandas/geopandas#903), but I would still have expected from conda to complain about not-satisfiable versions or something like that.

Me too :-(

> So metadata does need curating, even old metadata baked into old packages.

Yep. Most of the time that is the culprit. We should remove old package from every-now-and-then to ensure a cleaner solution of packages, but that is very controversial.

> without any pinnings to old packages, except that it is for python 3.5:

Sorry, that won't work at all b/c conda-forge dropped Python 3.5 a while back and all 3.5 packages are outdated. If that is really important and upgrade to Python 3.6 is impossible we can make one-time builds of it.

**Comment by jorisvandenbossche** [comment]
> Sorry, that won't work at all b/c conda-forge dropped Python 3.5 a while back and all 3.5 packages are outdated. If that is really important and upgrade to Python 3.6 is impossible we can make one-time builds of it.

It's not about being able to upgrade to Python 3.6 in this case, but about testing on our CI for a range of versions. So it don't have to be up to date packages, I was mainly looking for a set of old packages that work on Python 3.5 (because I suppose at one point in time, this worked in Python 3.5)

**Comment by ocefpaf** [comment]
> It's not about being able to upgrade to Python 3.6 in this case, but about testing on our CI for a range of versions. So it don't have to be up to date packages, I was mainly looking for a set of old packages that work on Python 3.5 (because I suppose at one point in time, this worked in Python 3.5)

I understand that but we (conda-forge) cut the support for Python 3.5 due to CI resources. I'll try to re-compiled the GIS stack for Python 3.5 once more over the weekend. I'll keep you posted. (BTW, did you try with the default channel? Ananconda has more resources than us and they are keeping Python 3.5 alive. If there are any packages missing we can negotiate with them to add it to the main channel.)

**Comment by mingwandroid** [comment]
Depends on the type of resource! We don't keep 3.5 going either. Our support is for latest 2.7.x and latest two 3.x only which is 3.7 and 3.6 only. The compiler switch over will have compounded problems for 3.5 too!

**Comment by mingwandroid** [comment]
Well we did build 3.5 with the 'new' compilers I suppose so it's maybe an idea for 3.5ers to use defaults? Maybe with conda-forge getting lower priority so I don't think it's really bad advice!

**Comment by jorisvandenbossche** [comment]
>  I'll try to re-compiled the GIS stack for Python 3.5 once more over the weekend.

@ocefpaf please, don't put your time in that :-) Or at least not just for me. If we want to keep python 3.5 testing on travis CI, I can also install rasterio with pip for that environment.

> BTW, did you try with the default channel?

Yes, but defaults has no rasterio 1.0 for python 3.5 (and I assumed we wanted at least >= 1 for rasterio, but in hindsight, I am actually not sure if contextily requires that, if not that is also an option)

> they are keeping Python 3.5 alive

What I suppose is maybe my misconception is that I assumed it was not needed to keep it "alive", as I would be fine with creating an environment with the packages built like a year ago. It was working a year ago, so if I can install exactly the same versions / builds, why would it not work now? But probably that is not that easy as it sounded to me .. ;)

**Comment by ocefpaf** [comment]
> What I suppose is maybe my misconception is that I assumed it was not needed to keep it "alive", as I would be fine with creating an environment with the packages built like a year ago. It was working a year ago, so if I can install exactly the same versions / builds, why would it not work now? But probably that is not that easy as it sounded to me .. ;)

Indeed but sometimes bad package metadata and poor env isolation will mix package with new compilers and pull binaries that are incompatible. Can you try the "old label?" Maybe that will work. It would be something like:


```
conda create --name TEST --channel conda-forge/label/cf201901 python=3.5 rasterio
```

**Comment by jorisvandenbossche** [comment]
Ah, that actually works! And is probably what I was looking for. 
Is this label assumed to stay?

**Comment by ocefpaf** [comment]
> Ah, that actually works! And is probably what I was looking for.
> Is this label assumed to stay?

Yes. However, we should remove it from `main` to prevent issues like the one you reported. Ping @mariusvniekerk ;-p
