### ISSUE TITLE
Cannot create environment with just gdal 2.3

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/gdal-feedstock#273]
I am trying to create an environment with gdal 2.3. A `conda search` (and looking at https://anaconda.org/conda-forge/libgdal/files?version=2.3.3) indicates that those packages exist, but trying to install it gives:
```
$ conda create -n test-gdal python=3.6 libgdal=2.3 -c conda-forge
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - libgdal=2.3
Use "conda search <package> --info" to see the dependencies for each package.
```

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
    active env location : /home/joris/miniconda3
            shell level : 1
       user config file : /home/joris/.condarc
 populated config files : /home/joris/miniconda3/.condarc
                          /home/joris/.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : /home/joris/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/joris/miniconda3/pkgs
                          /home/joris/.conda/pkgs
       envs directories : /home/joris/miniconda3/envs
                          /home/joris/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.7.1 Linux/4.4.0-143-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by kmuehlbauer** [comment]
@jorisvandenbossche The package in the list you linked is marked broken. This has been the time of the great compiler transition. Anyway, there are packages with version 2.3.2 under the `gcc7` label (new compilers) and `cf201901` label (old compilers) which you can install with:

```conda create -n test-gdal python=3.6 gdal=2.3 -c conda-forge/label/gcc7```

or

```conda create -n test-gdal python=3.6 gdal=2.3 -c conda-forge/label/cf201901```

**Comment by jorisvandenbossche** [comment]
Ah, didn't notice the "broken" label. 
But for gdal 2.3.2, I thought that the new compilers (gcc7) became the new default, so why doesn't it find it automatically? Or for that, it should actually be labeled with "main" ?

**Comment by jorisvandenbossche** [comment]
Do you know what the reason is that the 2.3.3 builds were labeled as broken? We were using them happily in the geopandas CI (see eg this build from 2 weeks ago: https://travis-ci.org/geopandas/geopandas/jobs/502574922#L726), but that started failing now (because it now gets gdal from defaults instead of conda-forge, because there is no gdal 2.3 available in the main conda-forge channel)

**Comment by kmuehlbauer** [comment]
Yes, normally, those packages with label `gcc7` should have been moved to `main` label. I have no idea why that did not happen. @ocefpaf might know, if there is some reason for it.

**Comment by kmuehlbauer** [comment]
> Do you know what the reason is that the 2.3.3 builds were labeled as broken?

No, sorry.

**Comment by jorisvandenbossche** [comment]
For context: we are trying to create a conda-forge based environment with gdal 2.3 on travis, to also have a test run with an older version of gdal (the yml file is here: https://github.com/geopandas/geopandas/blob/master/ci/travis/36-pd020.yaml, there are also other version pins (for pandas and matplotlib), but even without those, we have the same problem of "gdal=2.3" being unsatisfiable)

**Comment by jorisvandenbossche** [comment]
@kmuehlbauer and thanks for the quick response!

**Comment by ocefpaf** [comment]
I need to rebuild 2.3 with latest openssl and other new dependencies. I'll do that later today and get back to you.

The reason it was removed was to make it easier for conda to solve environments with conda-forge and defaults. Now that we are recommending `strict` we don't have to do that.

**Comment by kmuehlbauer** [comment]
@ocefpaf I remember you explained that `strict` stuff last days to someone (difference in handling linux/windows because of numpy/mkl), but I lost that. Could you point me to this again?

**Comment by ocefpaf** [comment]
> @ocefpaf I remember you explained that `strict` stuff last days to someone (difference in handling linux/windows because of numpy/mkl), but I lost that. Could you point me to this again?

Good question. That is actually solved now thanks to the amazing blas wizard @isuruf. So now we can use `strict` in both Windows, Linux, and macOS. And, if you find any problems, we can actually solve them if you are using `strict`. (Without `strict` it becomes just a race of channels and we cannot solve anything in the long term.)

**Comment by kmuehlbauer** [comment]
Perfect, so I just add this to my `.condarc` and I'm done. Great work!

**Comment by ocefpaf** [comment]
> Perfect, so I just add this to my `.condarc` and I'm done. Great work!

There may still be problems but at least they are problems we can do/should something  about them :smile:

**Comment by cpaulik** [comment]
Is the plan to rebuild or re-label older gdal versions or will they stay in the `conda-forge/label/cf201901` label?

**Comment by ocefpaf** [comment]
It was rebuilt but be aware that we may not have all the downstream dependencies built for it. For example, I'm not sure you'll be able to install `fiona` with it.

**Comment by jorisvandenbossche** [comment]
> For example, I'm not sure you'll be able to install fiona with it.

That seems to be working: https://travis-ci.org/geopandas/geopandas/jobs/509802484

Thanks for the update!
