### ISSUE TITLE
libkea.so.1.4.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sgillies** [conda-forge/gdal-feedstock#276]
Rasterio's documentation on RTD depends on conda-forge's GDAL, which is unusable at the moment (see https://readthedocs.org/projects/rasterio/builds/8800394/):

```
WARNING: autodoc: failed to import module 'rasterio'; the following exception was raised:
libkea.so.1.4.7: cannot open shared object file: No such file or directory
```

I realize that conda-forge attempts to reconcile a large number of independent projects into one working system and that the latest versions can't be perfectly reconciled all the time. Is there a known good set of conda-forge packages that can provide a working GDAL? I'm fine with somewhat older versions of packages. GDAL 2.2 would be fine.

**Comment by kmuehlbauer** [comment]
@sgillies Looking at the docs I'm thinking that the part where rdt installs `mock`, `pillow` etc might pull in things from defaults channel.

To rule this out, could you add some `conda list` output to your conf.py?

**Comment by ocefpaf** [comment]
That sure looks like a bad channel mix, conda-forge is on `kealib 1.4.10` for a while now but `defaults` is still on `kealib 1.4.7`. Can you enable the strict channel option on RTD?

**Comment by sgillies** [comment]
@ocefpaf unfortunately, it looks like channel_priority is not valid in an environment.yml file.

```
EnvironmentSectionNotValid: The following section on '/home/sean/projects/rasterio/environment.yml' is invalid and will be ignored:
 - channel_priority
```

It's not clear to me whether a .condarc file is a solution for RTD because we can't easily write to the root or user directory and I don't see any sign that a .condarc file in the project root (working directory) will be used.

Would directing conda to get mock, pillow, etc using pip be a possible solution? Would that sidestep the channel conflicts?

**Comment by ocefpaf** [comment]
> @ocefpaf unfortunately, it looks like channel_priority is not valid in an environment.yml file.

You would need to issue these command to set that in the `.condarc`, not sure if RTD allows that though:

```
conda config --add channels conda-forge
conda config --set channel_priority strict
```

> It's not clear to me whether a .condarc file is a solution for RTD because we can't easily write to the root or user directory and I don't see any sign that a .condarc file in the project root (working directory) will be used.

I don't really know how RTD works, sorry.

> Would directing conda to get mock, pillow, etc using pip be a possible solution? Would that sidestep the channel conflicts?

That should work. Another option would be to use only `defaults` if you do not need packages from `conda-forge`.

(I would recommend only `conda-forge` but one cannot exclude `defaults` based only on the `environment.yaml` file, you would need to issue a config command like the ones above.)

**Comment by sgillies** [comment]
I'm sad to delete the conda-forge channel, but that's what I've done. I'll try to find the time to ask RTD about providing more control over the conda config. @ocefpaf @kmuehlbauer thanks for the help!
