### ISSUE TITLE
ge vs default

### ISSUE THREAD

**Issue by milanoleonardo** [conda-forge/gdal-feedstock#282]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ocefpaf** [comment]
Closing this b/c there are not enough details to understand the issue. Please be more descriptive if you have questions/issues for the gdal feedsrock team.
