### ISSUE TITLE
GDAL > 2.0.0

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/gdal-feedstock#3]
Is there a gdal2 feedstock somewhere, or in planning. I'm trying to set this up locally, but with condaforge it seems much nicer.

**Comment by ocefpaf** [comment]
> Is there a gdal2 feedstock somewhere, or in planning. I'm trying to set this up locally, but with condaforge it seems much nicer.

There is no planning right now.  We added the gdal 1.x series because of `fiona` and `rasterio`.  What are the short comings of the default channel gdal 2?  I can help you set a feedstock if you want to be the maintainer of such a package.

**Comment by kmuehlbauer** [comment]
The problem is with gdal dependencies not met in default channel.

I need gdal with libhdf5, libnetcdf, libgeos but python27 and python34 have no geos available in the default channel. Only python35 does. Few days before things worked like charm within miniconda/travis for all three but now... broken.

My knowledge of conda and recipes is quite limited. If adapting the https://github.com/conda/conda-recipes/tree/master/gdal recipe to build from svn-trunk on a local conda installation is good enough I can give it a try. But my working OS is linux64, I could use help for setting this up for other OS.

**Comment by ocefpaf** [comment]
> I need gdal with libhdf5, libnetcdf, libgeos but python27 and python34 have no geos available in the default channel. Only python35 does. Few days before things worked like charm within miniconda/travis for all three but now... broken.

Awesome!  That is exactly what conda-forge is all about. Although, the long-tem goal is to fold those back into the default channel! Ping @msarahan and @pelson.

> But my working OS is linux64, I could use help for setting this up for other OS.

No problem.  The starting point is to send a PR to https://github.com/conda-forge/staged-recipes/tree/master/recipes. We can move this thread there once you set a first draft of your PR.

**Comment by kmuehlbauer** [comment]
OK, so I fork the linked repo and add the recipe? I just check everything locally...

**Comment by ocefpaf** [comment]
> OK, so I fork the linked repo and add the recipe? I just check everything locally...

Yes.  I will help you from there. Once we have a working PR we merge it and the feedstock will be automatically created.

**Comment by pelson** [comment]
Actually @ocefpaf, I'm kind of wondering whether to make a 1.x and a 2.x branch in this feedstock. There are a few places I've not even started looking at branches properly in the automation, but it has always been my intention to allow such a thing (think py2 and py3). It might make sense to start with something less big than GDAL, but certainly sounds like a sensible use-case.

**Comment by ocefpaf** [comment]
Makes sense.  I jumped the gun sending @kmuehlbauer to staged-recipes in an attempt to attract more maintainers by showing them the workflow to submit a recipe. 

Maintaining different versions of the same package will be a challenge. (But hopefully we can avoid te udunits vs udunits2 naming problem :wink:)

**Comment by kmuehlbauer** [comment]
@ocefpaf No problem on my side. How is this going further now?

**Comment by ocefpaf** [comment]
Here is what I suggest we do:

- wait for @pelson on his branch plan to keep two different versions side-by-side.(He is away until next thought.)
- while we wait for him we can work on this PR to get it in shape (get it to compile in all CIs).  Even if we close this PR we will use this recipe.

That won't give you a package to test tomorrow, sorry. Are you OK with that plan?

**Comment by kmuehlbauer** [comment]
@ocefpaf That's fine. I think the linux64 version on travis compiles already, but has stopped due to long logfile. Having a look into it tomorrow.

**Comment by ocefpaf** [comment]
> @ocefpaf That's fine. I think the linux64 version on travis compiles already,

Travis-CI is our "OS X."

>  but has stopped due to long logfile. Having a look into it tomorrow.

Don't worry about that. I haven't find a solution for this yet.  If one of the gdal's got built the test will too and we can re-start the Travis-CI until they are all uploaded.

**Comment by pelson** [comment]
@ocefpaf - a PR which updates the feedstock can be proposed (and CI systems can cycle). Once happy, instead of merging, put the proposed branch onto this feedstock. Shouldn't need anything from me for that.

I'd go for it, and I'll have to fix anything that comes out of it (it can't be too bad, right? [otherwise it is a pretty fragile system] :wink: )

**Comment by ocefpaf** [comment]
> Shouldn't need anything from me for that.

And here I thought you would come with another conda-bot to this :wink: 

@kmuehlbauer Let's do that!

**Comment by kmuehlbauer** [comment]
Sure, so it will be another branch of the existing gdal-feedstock?

**Comment by pelson** [comment]
> Sure, so it will be another branch of the existing gdal-feedstock?

Exactly. In order to make sure it is doing what you want, I'd propose a PR which moves everything up to vn2, and once everything goes green, we don't merge it but create a new branch from it *on this feedstock*.

:+1:

**Comment by kmuehlbauer** [comment]
@pelson So I fork from here and make the changes for version2. Then I can close this pr conda-forge/staged-recipes#82, correct?

**Comment by pelson** [comment]
Yep. If you're happy to do that, that would be awesome. Fork from this repo :+1: .

**Comment by kmuehlbauer** [comment]
#5 here we go

**Comment by kmuehlbauer** [comment]
@ocefpaf Thanks for merging. But we have to review the dependencies:

```
(test_forge1)k.muehlbauer@KaiBox:~> conda install -f --channel https://conda.anaconda.org/conda-forge gdal=2.0.2=np110py27_0 --no-deps
Fetching package metadata: ............
Solving package specifications: ....

The following specifications were found to be in conflict:
  - gdal 2.0.2 np110py27_0 -> kealib
Use "conda info <package>" to see the dependencies for each package.
(test_forge1)k.muehlbauer@KaiBox:~>
```
conda version is 4.0.4

Dependencies for kealib:

```
kealib 1.4.5 8
--------------
file name   : kealib-1.4.5-8.tar.bz2
name        : kealib
version     : 1.4.5
build number: 8
build string: 8
channel     : osgeo
size        : 227 KB
arch        : x86_64
binstar     : {u'package_id': u'53afe027e1dad15a3fa0b5be', u'channel': u'main', u'owner_id': u'53aa99f55e768369e1c4679b'}
license     : MIT
machine     : x86_64
md5         : 343e7a5da034cf1899c81c6a0ca3d486
operatingsystem: linux
platform    : linux
subdir      : linux-64
target-triplet: x86_64-any-linux
installed environments:
dependencies:
    gdal 1.11.2
    hdf5 1.8.15.1
    zlib
```

I did not manage to force-install gdal 2.0.2. Is this circular `kealib`-dependency correct?

**Comment by ocefpaf** [comment]
I believe that `kealib` from the `default` channel does not have that dependency on `gdal` because `conda install -c conda-forge gdal==2.0.2` worked for me.

Note that you are installing the one from `osgeo`. I am not sure that `kealib` does depend on `gdal` can you check that?

**Comment by groutr** [comment]
Thought I would pop in here.  I've maintained the gdal stack in the past.
@ocefpaf, you're correct.  `kealib` from `default` only has a runtime dependency on hdf5.

**Comment by kmuehlbauer** [comment]
I'm a bit confused now... I removed the osgeo channel from `.condarc` and it worked. Thanks @ocefpaf I didn't look at the channel.

**Comment by kmuehlbauer** [comment]
Yes, it works now, was an issue with the osgeo channel. I'll test all the 2.0.2 linux packages later.

**Comment by ocefpaf** [comment]
Thanks for the info @grout. @kmuehlbauer can we close the issue?

**Comment by kmuehlbauer** [comment]
Yes, issue resolved! Thanks @ocefpaf and @pelson for the guidance and help. I hope that the windows version pop up when appveyor did it.

**Comment by ocefpaf** [comment]
>  I hope that the windows version pop up when appveyor did it.

AppVeyor is slow. We need to check again tomorrow and, if the files are not there, we might need to re-start it.

**Comment by pelson** [comment]
Thanks to @kmuehlbauer & @ocefpaf for working on this.
@groutr - are you interested in becoming a maintainer of this recipe along with @kmuehlbauer and @ocefpaf? Your experience would really be a massive boon, and I'm hopeful that in time Continuum will be able to draw from this gdal feedstock as its canonical recipe.

:+1:

**Comment by ocefpaf** [comment]
> @groutr - are you interested in becoming a maintainer of this recipe 

:+1:
