### ISSUE TITLE
GDAL header files or devel package

### ISSUE THREAD

**Issue by hetsch** [conda-forge/gdal-feedstock#308]
This is not an issue per se, but more a question how to obtain the header files of the GDAL build. The reason I'm asking this is that I need to compile another C++ programm that needs the header files of GDAL for a successful compile run. Any ideas how to solve this issue? I'm a conda rookie, so I might have easily overseen something.

Thank's in advance!

**Comment by gillins** [comment]
The header files should be installed with the `gdal` package - we don't have separate devel packages. If you are in an activated conda environment with `gdal` installed the headers should be found under `$CONDA_PREFIX/include` and the libs under `$CONDA_PREFIX/lib`. Let me know if that is unclear.
