### ISSUE TITLE
Build with userfaultfd support

### ISSUE THREAD

**Issue by piyushrpt** [conda-forge/gdal-feedstock#323]
Issue:

GDAL is currently not being built with userfaultfd support. We rely on conda for teaching GDAL and related GIS tools with a jupyterhub setup; and currently can't use the new vsis3 features for NETCDF datasets (e.g, from JPL's ARIA system/ ASF SAR archive). Looking through the azure pipelines and https://github.com/OSGeo/gdal/issues/1328 - its probably because of "userfaultfd" presence and usability are reported as "no" by configure - https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=55722. 

Would it be possible to enable "userfaultfd" support for conda-forge builds?

<br/>
Environment:

Standard linux x86_64 with gdal 3.0.1 installed via conda_forge (no other packages explicitly installed).

```
$ conda info
     active environment : gdal3
    active env location : /scratch/agram/python/miniconda3/envs/gdal3
            shell level : 2
       user config file : /home/agram/.condarc
 populated config files : /home/agram/.condarc
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=10.1
       base environment : /scratch/agram/python/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /scratch/agram/python/miniconda3/pkgs
                          /home/agram/.conda/pkgs
       envs directories : /scratch/agram/python/miniconda3/envs
                          /home/agram/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/3.10.0-957.10.1.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 42464:1001
             netrc file : /home/agram/.netrc
           offline mode : False
```

**Comment by ocefpaf** [comment]
> Would it be possible to enable "userfaultfd" support for conda-forge builds?

Sure. Do you want to send a PR adding that feature?

**Comment by piyushrpt** [comment]
@ocefpaf Happy to do it. Any suggestions on how to get the pre-reqs for this? Might need yum requirements. Will look into this.
