### ISSUE TITLE
HDF5_H5_IS_DLL variable for GDAL 3.1 makefiles

### ISSUE THREAD

**Issue by hobu** [conda-forge/gdal-feedstock#337]
Upstreaming the HDF5 patch.

https://github.com/OSGeo/gdal/pull/1931

**Comment by ocefpaf** [comment]
Awesome! Thanks!! Let's keep this open until a new verions of gdal is out and we can drop the patch here.

**Comment by rouault** [comment]
This was backported in GDAL 3.0.3

**Comment by ocefpaf** [comment]
> This was backported in GDAL 3.0.3

Thanks. I'll start a new build dropping the patch.

**Comment by ocefpaf** [comment]
Actually, @gillins already did it.

xref.: https://github.com/conda-forge/gdal-feedstock/pull/363/commits/26a63392f07af5c8b05b99fb2b969d5b490cecde
