### ISSUE TITLE
poppler 0.76 reference

### ISSUE THREAD

**Issue by hobu** [conda-forge/gdal-feedstock#357]
One of GDAL's dependencies has a poppler 0.76 reference in rpath or somewhere. I'm seeing it on both linux and osx.

```
dyld: Library not loaded: @rpath/libpoppler.76.dylib
2:   Referenced from: /usr/local/miniconda/envs/pdal/lib/libgdal.26.dylib
```

**Comment by hobu** [comment]
On OSX, I get 0.83.0
`conda install -c conda-forge gdal` == poppler 0.83.0
```
  poppler            conda-forge/osx-64::poppler-0.83.0-hac18326_0
  poppler-data       conda-forge/noarch::poppler-data-0.4.9-1
```

**Comment by hobu** [comment]
https://github.com/conda-forge/gdal-feedstock/blob/master/.ci_support/osx_.yaml#L117 is set to 0.67.0, however

**Comment by ocefpaf** [comment]
`conda install -c conda-forge gdal` hides some things. Do you have the conda-forge channel on top of `defaults` and are you using `strict` channel option, [see this for more info](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge)?

I cannot reproduce that on Linux in a clean env:

```shell
conda create --name TEST gdal
conda activate TEST
conda list | grep poppler
poppler                   0.67.0               h14e79db_8    conda-forge
```

**Comment by hobu** [comment]
The init for PDAL where this is happening is https://github.com/PDAL/PDAL/blob/master/scripts/azp/osx.yml#L30

**Comment by hobu** [comment]
Indeed it looks like there's a libgdal-3.0.2  in defaults now with a different poppler pin.

**Comment by ocefpaf** [comment]
> Indeed it looks like there's a libgdal-3.0.2 in defaults now with a different poppler pin.

still, your configuration there should prevent that one from getting selected. I'll dig into this as soon as possible (working on some fun day-job reports this week.)

**Comment by hobu** [comment]
> still, your configuration there should prevent that one from getting selected

I had updated it to put the `strict` call in, so I think there is no bug. I hadn't ever needed to do it before, however, because the GDAL in default was also way too old.

**Comment by ocefpaf** [comment]
On macOS, and I believe Linux too, you can even remove defaults entirely these days thanks to @isuruf's efforts to add the compilers runtimes on conda-forge.
