### ISSUE TITLE
PROJ 7.2

### ISSUE THREAD

**Issue by snowman2** [conda-forge/gdal-feedstock#421]
Has GDAL been rebuild with PROJ 7.2 yet?

**Comment by ocefpaf** [comment]
[Nope](https://github.com/conda-forge/gdal-feedstock/blob/master/.ci_support/linux_64_.yaml#L115). According to the [status page](https://conda-forge.org/status/#proj720) it is stuck in https://github.com/conda-forge/libspatialite-feedstock/pull/57
