### ISSUE TITLE
error in import gdal as: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev 

### ISSUE THREAD

**Issue by abhiatmos** [conda-forge/gdal-feedstock#446]
After getting install gdal package from conda using the following command:
conda install -c conda-forge gdal
conda install -c conda-forge/label/cf202003 gdal
conda install -c conda-forge/label/gcc7 gdal
conda install -c conda-forge/label/broken gdal
conda install -c conda-forge/label/TEST gdal
conda install -c conda-forge/label/cf201901 gdal

I am getting error in import gdal package from python as:

import gdal
Traceback (most recent call last):
File "", line 1, in
File "/home/abhi/anaconda3/lib/python3.7/site-packages/gdal.py", line 2, in
from osgeo.gdal import deprecation_warn
File "/home/abhi/anaconda3/lib/python3.7/site-packages/osgeo/init.py", line 26, in
_gdal = swig_import_helper()
File "/home/abhi/anaconda3/lib/python3.7/site-packages/osgeo/init.py", line 22, in swig_import_helper
_mod = imp.load_module('_gdal', fp, pathname, description)
File "/home/abhi/anaconda3/lib/python3.7/imp.py", line 242, in load_module
return load_dynamic(name, filename, file)
File "/home/abhi/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
return _load(spec)
ImportError: /home/abhi/anaconda3/lib/python3.7/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev

kindly, any one can solve this issue.

Thanks in advance.....

**Comment by akrherz** [comment]
Why would you install gdal in that manner?  Just the first command would be sufficient.

**Comment by ocefpaf** [comment]
@abhiatmos you are using multiple labels and it looks like you don't really knowing what they are for. Including broken and TEST! I'm closing this issue. If you are still experiencing problems please open a new one with the required debug information on the issue template.
