### ISSUE TITLE
ARM64 Build

### ISSUE THREAD

**Issue by venabled** [conda-forge/gdal-feedstock#463]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I was wondering in general what it would take to get an arm64 build of GDAL going on conda-forge, and if I can help make it happen. My guess is that it's mostly going through the extensive dependency list and making sure those are built?

**Comment by ocefpaf** [comment]
> My guess is that it's mostly going through the extensive dependency list and making sure those are built?

Pretty much :smile: 

The bot is sending the PRs in "topological" order. The current package that is blocking it is https://github.com/conda-forge/libspatialite-feedstock/pull/67

**Comment by gillins** [comment]
Just to clarify: https://github.com/conda-forge/libspatialite-feedstock/pull/67 is for OSX Arm64, https://github.com/conda-forge/libspatialite-feedstock/pull/68 is for linux Arm64. Both are failing ATM...

**Comment by ocefpaf** [comment]
Sorry. I see arm64 and I fall for the mac M1 trap ;-p
Indeed they are different things but sadly they are both failing.

**Comment by venabled** [comment]
I'm amazed with all the great work and automation magic here in the conda-forge world. 

Looks like spatialite built and it's failing on hdf4.

**Comment by xylar** [comment]
The Linux migration to ARM64 happened in https://github.com/conda-forge/gdal-feedstock/pull/466 and the OSX migration in https://github.com/conda-forge/gdal-feedstock/pull/482.  I believe this can be closed.
