### ISSUE TITLE
Using libjpeg-turbo instead of libjpeg

### ISSUE THREAD

**Issue by rouault** [conda-forge/gdal-feedstock#486]
I might be wrong, but it seems to me that the GDAL build uses IJG libjpeg, and not libjpeg turbo (https://github.com/conda-forge/libjpeg-turbo-feedstock). The later is what has been used for years by many Linux distro as their system libjpeg. It offers substantial speedups

**Comment by gillins** [comment]
You are indeed correct. I think there was an issue with other parts of the conda-forge stack requiring IJG libjpeg. Is this still the case @ocefpaf @isuruf ?

**Comment by isuruf** [comment]
See https://github.com/conda-forge/conda-forge.github.io/issues/673.

**Comment by gillins** [comment]
Thanks @isuruf I must admit I got lost in this discussion. Should we be migrating `gdal` to turbo, or not yet?

**Comment by isuruf** [comment]
Not yet. It should be done globally or not at all.

**Comment by ocefpaf** [comment]
This migration has been planned for a while now. I guess we should start it sooner later than later. I'll bring revisit the issue and get us talking about it again.

**Comment by rouault** [comment]
Moving away from libjpeg-9d seems to be quite a urgent topic. I've discovered lately that libjpeg 9d caused libtiff to produce broken JPEG-compressed TIFF files (but likely not when used by the GDAL GeoTIFF driver, since it uses a non-default value for the JPEGTABLESMODE setting). See https://www.asmail.be/msg0055092297.html . But more generally, a number of people consider that the group behind IJG since release 7 can no longer be trusted.

**Comment by rouault** [comment]
It would be nice if that could move forward

**Comment by rouault** [comment]
One extra motivation for libjpeg-turbo is that the 2.2 release (not yet released) will get support for both 8-bit and 12-bit JPEG in the same build. 12-bit JPEG will now have the possibility of being full mainstream. libtiff 4.5dev and GDAL 3.7dev have been adapted to support that dual bit-depth capability (GDAL 3.6.1 will receive a minimum fix to make it work with its hacky internal copy of libjpeg 6b built as 12 bit)

**Comment by ocefpaf** [comment]
> Not yet. It should be done globally or not at all.

I'll add this to the agenda for our next meeting. We need to start this ASAP.

**Comment by akrherz** [comment]
It looks like libjpeg-turbo migration will get to GDAL [soon](https://conda-forge.org/status/#other_migrations).  Are there any build configuration changes we need here or can we just take the migration verbatim?

**Comment by rouault** [comment]
> Are there any build configuration changes we need here or can we just take the migration verbatim?

Just having libjpeg-turbo as dependency should be enough. GDAL CMake should be happy without any extra change.

**Comment by akrherz** [comment]
refs #731 #732

**Comment by eddy-geek** [comment]
for documentation purpose in case people google their upgrade issues, I had the following experience to upgrade:

```
❯ mamba update --all   # gdal is stuck on old versions:
  - gdal                              3.4.2  py310h8172e47_4      conda-forge                    
  + gdal                              3.5.0  py310h8172e47_1      conda-forge/linux-64        2MB

❯ mamba install gdal=3.6.3
Encountered problems while solving:
  - package gdal-3.6.3-py310hbad6b5a_3 requires libgdal 3.6.3 h0e7c1b1_3, but none of the providers can be installed

❯ mamba install libgdal=3.6.3
package libgdal-3.6.3-h0e7c1b1_3 requires libjpeg-turbo >=2.1.5.1,<3.0a0, but none of the providers can be installed

❯ mamba install libjpeg-turbo=2.1.5.1
Encountered problems while solving:
  - package libjpeg-turbo-2.1.5.1-h0b41bf4_0 has constraint jpeg <0.0.0a conflicting with jpeg-9e-h166bdaf_2

❯ mamba remove jpeg
#  removes bokeh, dask, geotiff, graphviz, gtk2, matplotlib, pillow, qt, rasterio, seaborn ...

# reinstall all useful packages removed above
❯ mamba install bokeh gdal>3.6.3 pillow rasterio seaborn pyqt
```

To be clear I'm happy about the change and it seems working as designed, although it might be confusing to some, and I expect a lot of people will "silently" stay on 3.5.0 until they recreate their env.

**Comment by ocefpaf** [comment]
> although it might be confusing to some, and I expect a lot of people will "silently" stay on 3.5.0 until they recreate their env.

Indeed. That can bite people. We usually recommend to always start a fresh env instead of updating. Envs in conda are "cheap" and keep environment.yaml and/or conda-lock files also help with reproducibility.

**Comment by rouault** [comment]
This ticket can be closed
