### ISSUE TITLE
FileGDB read/write support

### ISSUE THREAD

**Issue by schierkolk** [conda-forge/gdal-feedstock#488]
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I would like to request that GDAL be built with FileGDB read/write support.
https://trac.osgeo.org/gdal/wiki/FileGDB

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by gillins** [comment]
We don't currently build FileGDB in conda-forge. Do you feel like submitting a recipe to https://github.com/conda-forge/staged-recipes ?

**Comment by klassenjs** [comment]
I have a 'filedgb-feedstock' recipe I made for a local conda gdal build that I would be willing to share.  

I doubt it is up to the standards for submission, but if someone could to use it as a starting point.  

I didn't think about upstreaming it because I figured the FileGDB license and that the libraries are only distributed as binaries would be non-starters for conda-forge.

**Comment by ocefpaf** [comment]
> I doubt it is up to the standards for submission, but someone could to use it as a starting point.

If you want please submit to https://github.com/conda-forge/staged-recipes for a review.

> I didn't think about upstreaming it because I figured the FileGDB license and that the libraries are only distributed as binaries would be non-starters for conda-forge.

Repackaging binaries can be a last resort if we cannot build it but we do require a license that allows redistribution. If that is not the case we can't publish the package.

**Comment by klassenjs** [comment]
It looks like the LICENSE.txt files in the https://github.com/Esri/file-geodatabase-api repo are Apache 2.0, but I don't see source code anywhere.  As far as I can tell the repo is just a bunch of ZIP files with binaries compiled for different environments.

**Comment by gillins** [comment]
>  As far as I can tell the repo is just a bunch of ZIP files with binaries compiled for different environments.

Yeah that was my understanding also - glad to have it confirmed. I suppose it is unlikely that ESRI will release the source code any time soon... So there is no license for the actual binaries? I couldn't see one anyway - we'd need one before proceeding.
