### ISSUE TITLE
Enabling LibKML Driver on Windows

### ISSUE THREAD

**Issue by asarmy** [conda-forge/gdal-feedstock#507]
- [x ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: This is related to [Enabling LibKML Driver #152](https://github.com/conda-forge/gdal-feedstock/issues/152), which is closed. The [Linux & Max builds](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/build.sh#L47) have the libkml driver enabled, but the [Windows build](https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/set_bld_opts.bat) does not (also indicated in the [comments here](https://github.com/conda-forge/libgdal-feedstock/pull/3)).

Could the libkml driver be added to the Windows conda-forge gdal package?

<br/>
Environment (<code>conda list</code>):

```
python --version
Python 3.7.10

gdalinfo --version
GDAL 3.3.1, released 2021/06/28
```
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
conda 4.10.3

```
</details>

**Comment by gillins** [comment]
I think Windows support for `libkml` was added after #152 so it got missed. Are you happy to submit a PR for this?

**Comment by asarmy** [comment]
@gillins I'm sorry, I'm not the right person for the PR, total newbie

**Comment by gillins** [comment]
OK I'll have a look at doing this
