### ISSUE TITLE
Unable to install gdal 1.11.4 through conda forge

### ISSUE THREAD

**Issue by ritviksahajpal** [conda-forge/gdal-feedstock#53]
I am trying to install gdal 1.11.4 like this:
`conda install -c conda-forge gdal=1.11.4`

When I try to import gdal
`python -c 'import gdal'`

I get this error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ritvik/anaconda2/lib/python2.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/Users/ritvik/anaconda2/lib/python2.7/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/Users/ritvik/anaconda2/lib/python2.7/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: dlopen(/Users/ritvik/anaconda2/lib/python2.7/site-packages/osgeo/_gdal.so, 2): Library not loaded: @rpath/libjpeg.8.dylib
  Referenced from: /Users/ritvik/anaconda2/lib//libjasper.1.dylib
  Reason: image not found

How do I fix this?
```

**Comment by ocefpaf** [comment]
Both `jasper` and `gdal` are pinned to `jpeg 9*`, so I am not sure why the `jpeg.8` there.

Can you try the following commands for me:

```shell
conda create -n GDAL python=3.4 gdal=1.11.4 --yes  -c conda-forge # installs only gdal
source activate GDAL
python -c "import gdal"
conda list
conda info
```

If the import is not successful please copy and paste the results of the last two commands here so we can try to debug this.

**Comment by ritviksahajpal** [comment]
ok, this works.

However, this is based on python3.4 whereas I am using python 2.7.11

Results from the last 2 commands are here:
```
# packages in environment at /Users/ritvik/anaconda2/envs/GDAL:
#
ca-certificates           2016.2.28                     0    conda-forge
curl                      7.45.0                        0    defaults
expat                     2.1.0                         1    conda-forge
freexl                    1.0.2                         0    conda-forge
gdal                      1.11.4              np111py34_7    conda-forge
geos                      3.4.2                         1    conda-forge
giflib                    5.1.2                         0    conda-forge
hdf4                      4.2.11                        2    conda-forge
hdf5                      1.8.15.1                      2    defaults
icu                       56.1                          2    conda-forge
jasper                    1.900.1                       2    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
krb5                      1.13.2                        0    defaults
libgcc                    4.8.5                         1    defaults
libiconv                  1.14                          1    conda-forge
libnetcdf                 4.3.3.1                       3    defaults
libpng                    1.6.21                        1    conda-forge
libspatialite             4.3.0a                        3    conda-forge
libtiff                   4.0.6                         4    conda-forge
libxml2                   2.9.3                         5    conda-forge
mkl                       11.3.1                        0    defaults
numpy                     1.11.0                   py34_0    defaults
openjpeg                  2.1.0                         5    conda-forge
openssl                   1.0.2h                        0    conda-forge
pip                       8.1.1                    py34_1    defaults
postgresql                9.1.4                         1    defaults
proj.4                    4.9.2                         0    conda-forge
python                    3.4.4                         0    defaults
readline                  6.2                           2    defaults
setuptools                20.7.0                   py34_0    defaults
sqlite                    3.9.2                         0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py34_0    defaults
xerces-c                  3.1.2                         0    defaults
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         0    defaults
```

--------
```
conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/ritvik/anaconda2  (writable)
  default environment : /Users/ritvik/anaconda2/envs/GDAL
     envs directories : /Users/ritvik/anaconda2/envs
        package cache : /Users/ritvik/anaconda2/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/osx-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ritvik/.condarc
    is foreign system : False
```

**Comment by ritviksahajpal** [comment]
Hmm, when I repeat your steps using python 2.7.11 instead, it also works,

```
conda create -n GDAL_2.7 python=2.7.11 gdal=1.11.4 --yes  -c conda-forge # installs only gdal
source activate GDAL_2.7
python -c "import gdal"
conda list
conda info
```

What am I doing wrong? Thank you so much for looking at this, really curious to see what is wrong with my setup.

**Comment by ocefpaf** [comment]
All I can think of is that your previous env was had a different `gdal` and or a forced downgrade of `jpeg`.

**Comment by kmuehlbauer** [comment]
@ritviksahajpal 

Try to add (`conda install <package>`) the packages of your previous env one by one. This way you may find the package which caused `jpeg` to downgrade. It would be good to know for the maintainers here, if there is something outside that could cause trouble.

**Comment by ocefpaf** [comment]
@ritviksahajpal this issue is due to the mixing of the default channel and conda-forge channel packages. There is not much we can do about it as we do need both most of the time! If you ever find the offending package that causes the downgrade please let us know.

Meanwhile I recommend you to use environments in your workflow, like the one above, that reduces the scope of the task and avoids this problem.

I am closing this as it is not a problem with conda-forge's gdal per se, but please feel free to continue discussing here with us the alternatives and workarounds to the problem.

**Comment by ritviksahajpal** [comment]
Thanks @ocefpaf  and @kmuehlbauer , so I first got this error when I installed gdal using the conda-forge recipy. Somehow it did not play nice with the gdal I already had. Totally agree re using environments, will do that now.

**Comment by ritviksahajpal** [comment]
Ok, seems like the libjasper on my machine needs libjpeg8.x and libgdal needs libjpeg9.x.

**Comment by ritviksahajpal** [comment]
seems to be related to https://github.com/conda-forge/jasper-feedstock/issues/2

**Comment by ocefpaf** [comment]
We ship our own `jasper` compiled against `jpeg 9`. So if you are inside a conda env that should not be a problem.

**Comment by ritviksahajpal** [comment]
thanks @ocefpaf , I have learnt the hard way and am using environments now. Everything is working now. thanks for the solution!

FYI, I found the package causing downgrade of libjpeg. It is iris (http://scitools.org.uk/iris/)

**Comment by ocefpaf** [comment]
How are you installing `iris`? We added iris to conda-forge recently and, if that is downgrading `libjpeg` we should fix that!

**Comment by ritviksahajpal** [comment]
I used the scitools channel: conda install -c scitools iris

**Comment by ocefpaf** [comment]
`Tsc`, `tsc` @pelson :disappointed: who is taking care of scitools channel nowadays :wink: 

@ritviksahajpal, jokes aside, the most up-to-date `iris` recipe is now in conda-forge.

PS: Fun fact `conda-forge` was born from the `scitools` channel.

**Comment by ritviksahajpal** [comment]
thanks @ocefpaf !

**Comment by pelson** [comment]
> Tsc, tsc @pelson :disappointed: who is taking care of scitools channel nowadays :wink:

Excellent question @ocefpaf. Truth be told, who is taking care of my own notifications (>1000 unread)? 😆 

Looks to me that the scitools channel isn't pinning some of the dependencies correctly (not a surprise, since we only just starting pinning stuff correctly on conda-forge):

```
conda execute conda-forge.github.io/scripts/list_deps.py scitools --dependencies jpeg --platform osx-64
Fetching package metadata: ..
jasper 1.900.1 2 osx-64            : jpeg
jasper 1.900.1 4 osx-64            : jpeg
jasper 1.900.1 5 osx-64            : jpeg
```

@ritviksahajpal - just for future reference, the output from https://github.com/conda-forge/gdal-feedstock/issues/53#issuecomment-218235423 would have been the smoking gun which told us that your environment had been polluted from something other than defaults and conda-forge channels.

Question is, how to proceed with the scitools channel. @rhattersley and I should sit down and discuss its future (i.e. how to remove it altogether).

> @ritviksahajpal, jokes aside, the most up-to-date iris recipe is now in conda-forge.

🎉  - thanks in no small part to the amazing work of @ocefpaf I hasten to add!

**Comment by ritviksahajpal** [comment]
thanks @pelson , this is helpful.

**Comment by rhattersley** [comment]
> @rhattersley and I should sit down and discuss its future (i.e. how to remove it altogether).

:+1:
