### ISSUE TITLE
Should `autogen.sh` be added to the linux recipe?

### ISSUE THREAD

**Issue by cmarmo** [conda-forge/gdal-feedstock#530]
Dear conda-forge maintainers, [gdal/#4499](https://github.com/OSGeo/gdal/pull/4499) has just been merged. Per [this comment](https://github.com/OSGeo/gdal/pull/4499#issuecomment-922119127) I have prepared a pull request to update the linux build recipe.
After looking at the CI checks I'm under the impression that only the releases are downloaded: they already contain the `.configure` file.
Is it worth it to modify the recipe? Should a PR in this direction be considered?

Thanks!

**Comment by gillins** [comment]
@cmarmo Yes - the current recipe downloads the release tarball. Will the releases always have a `configure` ready to use? If so, would there be any benefit from running `autogen.sh` ?

**Comment by cmarmo** [comment]
I believe the `./configure` will be shipped with the release tarball (at least the `mkgdaldist.sh` script has been modified in this direction... :) ).
If the github repo is not downloaded, no need to use `.autogen.sh`.
Thanks for your answer. This can be closed.
