### ISSUE TITLE
GDAL_DATA environment variable not set in Windows

### ISSUE THREAD

**Issue by jobar8** [conda-forge/gdal-feedstock#54]
Hi,
I am working on Windows 10 and I have installed gdal using:
```
conda config --add channels conda-forge
conda install gdal
```
However, it does not set (or reset) GDAL_DATA. First, I had GDAL_DATA already defined from a previous installation, but it did not point to the right folder so my scripts did not work. Then I deleted it and re-installed gdal but that did not work either. The environment variable is not defined.

BTW, I am using Python 2.7 and Anaconda 4.0.0.
Thanks.

**Comment by ocefpaf** [comment]
@jobar8 I am not sure if the `GDAL_DATA` will be activated in a root installation of `gdal`. Can you try installing `gdal` in a separated env and test your script?

```shell
conda create -n GDAL python=3.4 gdal -c conda-forge
activate GDAL
<test_script>
```

Note that you can change the python version there for the one you want (We have `gdal` for 2.7, 3.4 and 3.5 available in conda-forge).

**Comment by jobar8** [comment]
I have tried again with:
```
conda create --name GDAL2 --channel conda-forge python=2.7 gdal=2.1.0
activate GDAL2
python script.py
```

My script fails calling `point.Transform(coordTrans)` where point is a geometry and coordTrans is a CoordinateTransformation. I get the following error: 
> "Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files."

Everything is fine once I set GDAL_DATA manually. 
Thanks.

**Comment by ocefpaf** [comment]
I will take a look. To be honest I always set that manually, so I don't really know how efficient the activate/deactivate script are.

**Comment by gillins** [comment]
This is a known problem under Windows (see https://github.com/conda/conda-env/issues/218). 

@msarahan - is there going to be a new conda release soon? This is bit unnerving for Windows users.

**Comment by gillins** [comment]
This appears to be fixed with the latest `conda`. @jobar8 can you try updating conda (`conda update conda`) and re-activating your environment and see if you can confirm this? Thanks

**Comment by jobar8** [comment]
I am not quite sure if that's fixed. When I started the anaconda prompt (before updating), I got this message I had never seen before:

`prepending C:\\Anaconda2 and C:\\Anaconda2\\Library\\mingw-w64\\bin and C:\\Anaconda2\\Library\\usr\\bin and C:\\Anaconda2\\Library\\bin and C:\\Anaconda2\\Scripts to PATH
(C:\Anaconda2) C:\Anaconda2\etc\conda\activate.d>if not defined GDAL_DATA (
set "GDAL_DATA=C:\Anaconda2\etc\conda\activate.d\\..\..\..\Library\share\gdal"
 set _CONDA_SET_GDAL_DATA=1
)`

Then I updated conda from 4.1.0 to 4.1.3. I created an environment GDAL2 the same way as before and my test script was working. But that could be because GDAL_DATA was already defined and pointing to `C:\Anaconda2\Library\share\gdal` because I also had a working GDAL installation in the root environment.

As a second test, I removed GDAL from the root environment and deleted GDAL_DATA from the Windows environment variables. I removed the GDAL2 environment I created earlier and re-created it. When I activate GDAL2 now, I get the first part of the message mentioned above (the bits added to PATH) but nothing about GDAL_DATA. And although I can import the osgeo module in python, the script that requires projection information is not working (error `Unable to open EPSG support file gcs.csv`)

**Comment by jobar8** [comment]
One more comment that might be useful: 
After re-installing GDAL in the root environment, things start to work again as previously, but only after I open a new Anaconda prompt. I get a message telling me that GDAL_DATA has been set. 
However, if I don't set GDAL_DATA manually in Windows, I can't get my script to work in a "normal" terminal (cmd.exe).

**Comment by msarahan** [comment]
The root environment is tricky.  It does not run the activate script, and
as such, does not set this environment variable for you.

In general, I hope you'll think about using environments.  They make these
kinds of problems not happen, and they're also a lot less troublesome
should anything with conda go wrong.

**Comment by jobar8** [comment]
But my experience today is that I need to install GDAL first on the root to get it working in a separate environment.

**Comment by gillins** [comment]
@msarahan I think there is something weird going on here. This was working for me last week, but with the latest conda, `GDAL_DATA` isn't being set when I activate an environment with `gdal` in it.

Should I open a issue on the Conda tracker?

**Comment by msarahan** [comment]
Sure.  I think it will work again in 4.1.4 - I had some dumb mistakes in 4.1.3.  For instance, we reverted CONDA_DEFAULT_ENV to its old behavior of sometimes being a name, and sometimes being a PATH.  We added CONDA_PREFIX to always be a PATH, but we didn't update the code that looks in activate.d for scripts to use it (still used CONDA_DEFAULT_ENV).  So, it probably was not finding these scripts. =(

4.1.4 should be out soon, if it isn't already.  let me know if it does not work.

**Comment by gillins** [comment]
You are totally right. I just updated to 4.1.4 and it works again :smile: Thanks!

**Comment by jobar8** [comment]
Sorry to resuscitate this issue but I don't think the gdal-activate.d script is working on Windows. 
I have created a new environment with Python 3.4, gdal 2.1.0 and a few other things. 
Running my scripts, I get the same error as before about GDAL_DATA not being set properly. Indeed, its value is "C:\Anaconda3\envs\interpies\etc\conda\activate.d\\..\..\..\Library\share\gdal"
Setting the environment variable manually to the correct folder makes things work but I thought I'd let you know about the issue.
Thanks.

**Comment by gillins** [comment]
It is working for me with the latest versions of everything. Can you try updating? The latest `gdal` is 2.1.1.

**Comment by dcsoft4** [comment]
I had this issue with Anaconda2 4.3.1.  I had to remove the double-quotes around the value of the GDAL_PATH environment variable.  Originally the batch file set 

    set GDAL_DATA="%~dp0\..\..\..\Library\share\gdal"

It worked after I changed it to 

    set GDAL_DATA=%~dp0\..\..\..\Library\share\gdal

**Comment by gillins** [comment]
Are you installing GDAL from conda-forge? If not please report this to the Anaconda team. GDAL 2.1.3 from conda-forge has this already set correctly (see https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/scripts/activate.bat#L7).

**Comment by dcsoft4** [comment]
I'm sorry, I'm fairly new.  I opened an Anacondra Prompt and typed `conda install gdal` which installed GDAL 2.1.0.

**Comment by gillins** [comment]
No worries - sorry I was a bit brief. I think you are looking for the Anaconda bug tracker (https://github.com/ContinuumIO/anaconda-issues). The Anaconda packages are managed by Continuum.

This bug tracker is for the conda-forge community maintained packages (see https://conda-forge.github.io/) which use different recipes (from this github repo). You can either swap to using conda-forge packages or try and get Continuum to fix this bug in Anaconda. I have previously tried to get them to fix this very bug, but I didn't have any luck....

**Comment by dcsoft4** [comment]
Thank you for all your help!  I have created an [Anaconda issue](https://github.com/ContinuumIO/anaconda-issues/issues/1564).
