### ISSUE TITLE
userfaultfd syscall is architecture dependent

### ISSUE THREAD

**Issue by rouault** [conda-forge/gdal-feedstock#580]
CC @piyushrpt 

The build recipe uses a https://github.com/conda-forge/gdal-feedstock/blob/master/recipe/userfaultfd.h include file that has a "#define __NR_userfaultfd 323" from asm-x86/unistd_64.h
Linux syscall numbers are generally architecture dependent, and userfaultfd is one of them as can be seen below 
```
/usr/include/valgrind/vki/vki-scnums-x86-linux.h:#define __NR_userfaultfd        374
/usr/include/valgrind/vki/vki-scnums-mips32-linux.h:#define __NR_userfaultfd		(__NR_Linux + 357)
/usr/include/valgrind/vki/vki-scnums-ppc64-linux.h:#define __NR_userfaultfd	364
/usr/include/valgrind/vki/vki-scnums-mips64-linux.h:#define __NR_userfaultfd            (__NR_Linux + 317)
/usr/include/valgrind/vki/vki-scnums-mips64-linux.h:#define __NR_userfaultfd             (__NR_Linux + 321)
/usr/include/valgrind/vki/vki-scnums-ppc32-linux.h:#define __NR_userfaultfd	364
/usr/include/valgrind/vki/vki-scnums-arm-linux.h:#define __NR_userfaultfd                388
/usr/include/valgrind/vki/vki-scnums-arm64-linux.h:#define __NR_userfaultfd 282
/usr/include/valgrind/vki/vki-scnums-amd64-linux.h:#define __NR_userfaultfd        323
```

So I suspect that userfaultfd is currently broken on Linux AARCH64 and PPC64

It would be more prudent to install the linux kernel header package (but perhaps there's none in Conda?) . Or modify recipe/userfaultfd.h to test for supported architectures and use a number that depend on them.

**Comment by xylar** [comment]
@piyushrpt, since you added this functionality in https://github.com/conda-forge/gdal-feedstock/pull/330, is this something you could help us fix?  Thanks very much in advance!

**Comment by gillins** [comment]
@izahn do you know anything about this? Does `linux-sysroot` contain the required Linux header files?

**Comment by izahn** [comment]
No it isn't included in `sysroot-linux*` packages. I don't know much about it, but based on the discussion in https://github.com/conda-forge/gdal-feedstock/pull/330 I we might be able to just delete that file and build with `cos7`.

**Comment by izahn** [comment]
My thought would be to use the centos kernel headers like this: https://github.com/conda-forge/gdal-feedstock/pull/604

Sadly that doesn't seem to work and would require additional effort to fix.

**Comment by piyushrpt** [comment]
I just got to this conversation. Somehow slipped under the radar during thanksgiving. Taking a look.

**Comment by piyushrpt** [comment]
I think this file enables the netcdf vsi features which are very useful. There are a couple of options, again I'm looking at qemu mailing lists since this solution was inspired by what they were doing. 

Option 1: Do something like this. Add any other archs as needed. For an unsupported archm Not defining __NR_userfaultfd should cause configure step to say userfaultfd is found but is not usable; and skip using it when it is not usable (hopefully). 

```
> #ifndef __NR_userfaultfd
> #ifdef __x86_64__
> #define __NR_userfaultfd 323
> #elif defined(__i386__)
> #define __NR_userfaultfd 374
> #elif defined(__powewrpc__)
> #define __NR_userfaultfd 364
> #endif
> #endif
```

Option 2: Just enable this on x86_64 with an if statement wrapping around it. 

If there is a preference, let me know

**Comment by izahn** [comment]
@piyushrpt what do you think about cleaning this up to use the `cos7` kernel headers instead of maintaining this locally? I implemented that version in https://github.com/conda-forge/gdal-feedstock/pull/604 but it would be great to get a second opinion about whether this is a good idea or not.
