### ISSUE TITLE
Python 3.4 32-bit failing on Windows/AppVeyor

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/gdal-feedstock#59]
Looks like GDAL builds are failing on Python 3.4 32-bit Windows. This started in the last couple builds. Seems to not be able to find `tiffio.h`. Sample failure in this [log]( https://ci.appveyor.com/project/conda-forge/gdal-feedstock/build/1.0.126/job/7ejmd7w95f0ys6qr#L1917 ).

**Comment by gillins** [comment]
I think TIFF_INC=%LIBRARY_INC% -> TIFF_INC=**-I**%LIBRARY_INC% in bld.bat might work. Seems to be missing a -I in front of the include path in the log. Don't know why if works for other combinations.
I'll submit a PR shortly.

**Comment by gillins** [comment]
See https://github.com/conda-forge/gdal-feedstock/pull/60.

I think something changed in the GDAL build between 2.0.2 and 2.1.0, seems the paths are specified differently. I don't know why the other configurations passed.
