### ISSUE TITLE
master branch build failed on macos openssl3

### ISSUE THREAD

**Issue by akrherz** [conda-forge/gdal-feedstock#595]
The master branch [build failed](https://github.com/conda-forge/gdal-feedstock/runs/4688009022) after the proj821 merge.  The failure was transient I think, but I don't seem to have the ability to restart this build.  Anybody here able to restart it?

**Comment by xylar** [comment]
There's likely not a better solution than pushing a dummy commit (e.g. add a blank line to the README) to make it rerun CI (for all builds).

**Comment by akrherz** [comment]
Thanks @xylar , I fixed the homepage URL within the `README.md`, :eyes: CI hoping for great success.

**Comment by akrherz** [comment]
CI all green, whew.
