### ISSUE TITLE
Reducing the build matrix

### ISSUE THREAD

**Issue by pelson** [conda-forge/gdal-feedstock#61]
Currently, whenever we do anything with GDAL, it consumes a huge amount of resource from AppVeyor and ends up queueing lots of things behind it. So the question is, are we able to reduce the build matrix for GDAL so that we don't end up building 12 variants (x86/x64, py27/py34/py35, np110/np111)? Looking at the download numbers, it isn't obvious that there are any variants which aren't downloaded, so it is a perfectly reasonable answer to say "no".

**Comment by gillins** [comment]
Good point. Is there a plan to obsolete py34 long term? Are there reasons why people can't move to py35?

I'm always surprised people are still using 32bit, but you are right - people are downloading it.

**Comment by pelson** [comment]
> Is there a plan to obsolete py34 long term?

Yes. We discussed this in the last meeting (minutes pending) and have agreed that we will not be providing py34 at the same time as py36 (end of this year). I'm interested in gradually fading py34 out, but on Windows, it seems that it still isn't easy to get hold of binaries for everything at py35 (VS 15).

I guess there is also an interesting question as to whether we really need np110 builds. That in itself would halve the build matrix.

**Comment by gillins** [comment]
I don't think numba yet supports np111. Maybe when it does then that would be a good time to drop np110?

**Comment by pelson** [comment]
Perhaps yes. I wouldn't have thought we would do that in general on conda-forge at that point, but I could conceive of doing it for the gdal feedstock to reduce the matrix.

This is really just something to think about - we don't need to force the reduction of the matrix, but it is worth keeping in mind if we see some easy wins.

**Comment by ocefpaf** [comment]
@pelson and @gillins maybe we should re-visit splitting the python bindings from the core lib. It won't help Windows that much as the Python bindings are light weight in comparison the the core lib.

**Comment by pelson** [comment]
> It won't help Windows that much as the Python bindings are light weight in comparison the the core lib.

Right, but we currently build GDAL 12 times due to the python deps, vs building it 2 twice without python bindings. My assumption is that building the python bindings is super quick compared to GDAL itself?

**Comment by gillins** [comment]
The Python bindings take 38 seconds to build on my machine - so yes much quicker than the core lib.

The core lib would still have to be built 3 times for Windows (one for each version of VS in use) - but yes splitting them up would speed up building for different versions of numpy etc.

**Comment by pelson** [comment]
> The core lib would still have to be built 3 times for Windows (one for each version of VS in use) - but yes splitting them up would speed up building for different versions of numpy etc.

Of course. I always forget that! Thanks for reminding me @gillins.

**Comment by gillins** [comment]
Maybe we can now remove numpy 1.10 since numba now supports 1.11?

**Comment by ocefpaf** [comment]
If we drop `numpy 1.10` we should drop everywhere and not only `gdal`. That is something that needs some discussion.

@gillins I can add that to the next meeting agenda and bring the topic. (Unless you want to wake up in the middle of the night to participate :wink:)

**Comment by gillins** [comment]
I'm really no good at having serious discussions in the middle of the night :smile: Whatever you guys decide is fine.

**Comment by ocefpaf** [comment]
Closing this b/c `AppVeyor` is quite fast now and I don't believe we need to reduce the build matrix for now.
