### ISSUE TITLE
Use cmake for build

### ISSUE THREAD

**Issue by zklaus** [conda-forge/gdal-feedstock#625]
### Comment:

It seems upstream is advocating the use of cmake even on windows (see [here](https://gdal.org/build_hints.html#build-gdal)). Would that be a good idea for conda-forge too?

**Comment by gillins** [comment]
I think the doco has go ahead of actual releases... AFAICT `gdal` 3.5.0 will be the first release with `cmake` support (see https://gdal.org/development/rfc/rfc84_cmake.html#phases-schedule). The existing build system will be removed in `gdal` 3.6.0 so we need to have done the migration by then...

**Comment by gillins** [comment]
I think we'd move to `cmake` also for Unix builds as well? Would be good to have them (more) consistent with Windows than they currently are...

**Comment by zklaus** [comment]
Agreed.  I was under the mistaken impression that the Linux build was already using cmake. Completely agree that we should use it for both.

**Comment by ocefpaf** [comment]
> Agreed. I was under the mistaken impression that the Linux build was already using cmake. Completely agree that we should use it for both.

That is mostly my fault. I've been planning to move to cmake on Windows for ages but kept postponing b/c I did not want to break anything. I guess it is time now, and the team here grew considerably, so with more eyes we can make this work without much trouble.

**Comment by zklaus** [comment]
@ocefpaf, don't worry. Following the upstream phases, the 2.5.x cycle seems to be the perfect time to do this.
