### ISSUE TITLE
LERC compression unknown with 3.4.2

### ISSUE THREAD

**Issue by aalcott** [conda-forge/gdal-feedstock#626]
### Comment:

**Under version 3.2 of gdal, we were running a program to build mrf files using the following commands**
self.outRaster = self.mrfDriver.Create( mrfFileName, self.config["numCols"], self.config["numRows"], 1, # number of bands, R G B self.config["dataType"], options=[ "Zsize={:d}".format(zSize), "UNIFORM_SCALE=2", # space for overviews self.config["MRF-OPTIONS"], "COMPRESS=LERC", "BlockSize={}".format(self.config["TILESIZE"]),
***the MRF-OPTIONS from our config file are "OPTIONS=V2=ON LERC_PREC=0.0001"
We recently updated to gdal 3.4.2 and have consistently received the error:**

`Traceback (most recent call last):
File "/opt/anaconda3/envs/gdalenv/lib/python3.9/multiprocessing/pool.py", lin
e 125, in worker
result = (True, func(*args, **kwds))
File "/opt/anaconda3/envs/gdalenv/lib/python3.9/multiprocessing/pool.py", lin
e 51, in starmapstar
return list(itertools.starmap(args[0], args[1]))
File "/home/arcgis/gis-project/src/master.py", line 65, in execute_task
gdalMrf.driver(dtg, doy)
File "/home/arcgis/gis-project/src/mrf.py", line 468, in driver
self.run_day(mrfDataPath, year, doy)
File "/home/arcgis/gis-project/src/mrf.py", line 347, in run_day
self.mrf_3d_files(mrfDataPath, sliceNumber, year, doy)
File "/home/arcgis/gis-project/src/mrf.py", line 253, in mrf_3d_files
self.create_mrf(
File "/home/arcgis/gis-project/src/mrf.py", line 128, in create_mrf
self.outRaster = self.mrfDriver.Create(
File "/opt/anaconda3/envs/gdalenv/lib/python3.9/site-packages/osgeo/gdal.py",
line 2001, in Create
return _gdal.Driver_Create(self, *args, **kwargs)
RuntimeError: GDAL MRF: Error setting compression
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/arcgis/gis-project/src/master.py", line 150, in
main(params)
File "/home/arcgis/gis-project/src/master.py", line 95, in main
res = pool.starmap(execute_task, inputData)
File "/opt/anaconda3/envs/gdalenv/lib/python3.9/multiprocessing/pool.py", lin
e 372, in starmap
return self._map_async(func, iterable, starmapstar, chunksize).get()
File "/opt/anaconda3/envs/gdalenv/lib/python3.9/multiprocessing/pool.py", lin
e 771, in get
raise self._value
RuntimeError: GDAL MRF: Error setting compression`

**We are using a pre-packaged version of gdal found on https://anaconda.org/conda-forge/libgdal. As shown below, it appears that the package is not built with the LERC functionality. Any assistance in enabling LERC compression with our new installation of gdal 3.4.2 would be greatly appreciated. Please let me know if you need more information.**

gdalinfo --format MRF
Format Details:
Short Name: MRF
Long Name: Meta Raster Format
Supports: Raster
Extension: mrf
Help Topic: drivers/raster/marfa.html
Supports: Open() - Open existing dataset.
Supports: Create() - Create writable dataset.
Supports: CreateCopy() - Create dataset by copying another.
Supports: Virtual IO - eg. /vsimem/
Creation Datatypes: Byte UInt16 Int16 Int32 UInt32 Float32 Float64

CreationOptionList
Option name="COMPRESS" type="string-select" default="PNG" description="PPNG = Palette PNG; DEFLATE = zlib "
ValueJPEG/Value
ValuePNG/Value
ValuePPNG/Value
ValueJPNG/Value
ValueTIF/Value
ValueDEFLATE/Value
ValueNONE/Value
ValueZSTD/Value
/Option
Option name="INTERLEAVE" type="string-select" default="PIXEL"
ValuePIXEL/Value
ValueBAND/Value
/Option
Option name="ZSIZE" type="int" description="Third dimension size" default="1" /
Option name="QUALITY" type="int" description="Compression dependent control value, for JPEG best=99, bad=0, default=85" /
Option name="BLOCKSIZE" type="int" description="Block size, both x and y, default 512" /
Option name="BLOCKXSIZE" type="int" description="Block x size, default=512" /
Option name="BLOCKYSIZE" type="int" description="Block y size, default=512" /
Option name="NETBYTEORDER" type="boolean" description="Force endian for certain compress options, default is host order" /
Option name="CACHEDSOURCE" type="string" description="The source raster, if this is a cache" /
Option name="UNIFORM_SCALE" type="int" description="Scale of overlays in MRF, usually 2" /
Option name="NOCOPY" type="boolean" description="Leave created MRF empty, default=no" /
Option name="DATANAME" type="string" description="Data file name" /
Option name="INDEXNAME" type="string" description="Index file name" /
Option name="SPACING" type="int" description="Leave this many unused bytes before each tile, default=0" /
Option name="PHOTOMETRIC" type="string-select" default="DEFAULT" description="Band interpretation, may affect block encoding"
ValueMULTISPECTRAL/Value
ValueRGB/Value
ValueYCC/Value
/Option
Option name="OPTIONS" type="string" description="
Compression dependent parameters, space separated:
ZSTD - boolean, enable libzstd as final stage, preferred over DEFLATE
DEFLATE - boolean, enable zlib as final stage
GZ - boolean, for DEFLATE enable gzip headers instead of zlib ones when using zlib
RAWZ - boolean, for DEFLATE disable all zlib headers
Z_STRATEGY - Z_HUFFMAN_ONLY | Z_FILTERED | Z_RLE | Z_FIXED: restricts DEFLATE and PNG strategy
OPTIMIZE - boolean, for JPEG, enables Huffman table optimization
" /
/CreationOptionList

OpenOptionList
Option name="NOERRORS" type="boolean" description="Ignore decompression errors" default="FALSE" /
Option name="ZSLICE" type="int" description="For a third dimension MRF, pick a slice" default="0" /
/OpenOptionList

**Comment by gillins** [comment]
Seems that there have been many changes to the MRF driver between these releases (https://github.com/OSGeo/gdal/commits/master/frmts/mrf)... 
I note that they have now added support for the external LERC library (https://github.com/OSGeo/gdal/pull/5386) which we do have in conda-forge so could potentially try this also.
I'd open an issue with GDAL and see what their response is. Failing that create a PR to add external `liblerc` support and see if that helps. Sorry I can't offer anything more concrete.

**Comment by rouault** [comment]
> I note that they have now added support for the external LERC library ([OSGeo/gdal#5386](https://github.com/OSGeo/gdal/pull/5386)) which we do have in conda-forge so could potentially try this also.

the pointed change is for GDAL 3.5.0

**Comment by gillins** [comment]
> the pointed change is for GDAL 3.5.0

Thanks @rouault any idea what might be going on with this message?

**Comment by rouault** [comment]
> any idea what might be going on with this message?

just that LERC compression is not enabled in the build for the MRF driver. Looking at https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/504325/logs/51, I see that there's an external liblerc that is detected, and thus it is used, which disables the Lerc codec in the MRF driver since it doesn't support in the 3.4 branch an external liblerc. A workaround for 3.4 would be to explicitly pass --with-lerc=internal to ./configure

**Comment by gillins** [comment]
Thanks @rouault - so this configuration should work with 3.5.0 right?

@aalcott can you confirm that this works with `gdal` 3.5.0 (builds should now be available on conda-forge)?

**Comment by aalcott** [comment]
This does work with gdal 3.5.0. Thank you for the help!
