### ISSUE TITLE
why `icu <70.1` still?

### ISSUE THREAD

**Issue by ngam** [conda-forge/gdal-feedstock#630]
### Comment:

I am not really sure how this works in general, but this feedstock seems to be at `icu <70.1` still. Is there a reason?

**Comment by akrherz** [comment]
See [conda-forge status](https://conda-forge.org/status/#icu70), we are being jammed up via qgis I believe.

**Comment by ngam** [comment]
It's actually this https://github.com/conda-forge/xerces-c-feedstock/pull/32/
