### ISSUE TITLE
ODBC should not be enabled with cmake on windows

### ISSUE THREAD

**Issue by akrherz** [conda-forge/gdal-feedstock#650]
I was rebuilding PDAL with build 2 (which I know was declared broken and pulled out), and I was getting an error on windows about msodbcsql17.dll

I think GDAL's CMake is maybe greedily pulling in ODBC, but we don't have the windows system dependency needed available to run, just to build. This is another thing to run down as part of the CMake migration. 

![image](https://user-images.githubusercontent.com/87751/191883823-3c4de4c4-a4dd-4899-a5b4-39d5838feadf.png)

_Originally posted by @hobu in https://github.com/conda-forge/gdal-feedstock/issues/629#issuecomment-1255749356_

**Comment by rouault** [comment]
should be solved with -DGDAL_USE_MSSQL_ODBC:BOOL=OFF

**Comment by hobu** [comment]
I wonder what system lib needs to be installed for it to work. I suppose that would be something the wider @conda-forge community would have to support. Not a big deal to live without it though.

**Comment by rouault** [comment]
> I wonder what system lib needs to be installed for it to work.

Likely "Microsoft ODBC Driver 17 for SQL Server" : https://learn.microsoft.com/en-us/sql/connect/odbc/download-odbc-driver-for-sql-server?view=sql-server-ver16#version-17  . This is pre-installed on github windows VM.

**Comment by akrherz** [comment]
Looking at our new 3.6.0 cmake build CI log files I find:
```
Found MSSQL_ODBC: C:/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/SDK/Lib/x64/msodbcsql17.lib (found version "17") 
 -- Disabled components:
   * ODBC component has been detected, but is disabled with GDAL_USE_ODBC=OFF
```

`recipe/bld.bat` has   `-DGDAL_USE_ODBC:BOOL=OFF`

[cmake hints](https://gdal.org/build_hints.html#odbc) seems to indicate that this setting overrides the MS one.  Is this issue still valid?

**Comment by zklaus** [comment]
I think this is resolved. I addressed it as part of the second attempt at Cmake. Please reopen if still valid.

**Comment by rouault** [comment]
-DGDAL_USE_ODBC:BOOL=OFF is quite drastic : it disables all ODBC functionality.
I believe you'd only want -DGDAL_USE_MSSQL_ODBC:BOOL=OFF as I suggested (there might have been confusion as the names are similar) to disable only the use of the *MSSQL* ODBC library, not base ODBC.
