### ISSUE TITLE
Add support for spatialite/sqlite

### ISSUE THREAD

**Issue by jgomezdans** [conda-forge/gdal-feedstock#66]
Spatialite (and sqlite) would be very nice to have. There's a conda-foge spatialite package, so this should be as simple as adding

    --with-sqlite3=$PREFIX \
    --with-spatialite=$PREFIX \

to `build.sh`, and to add dependencies to `sqlite` and `libspatialite` in `meta.yaml` (both for compile and run times). This seems to be working on Linux, and I guess it would also work for OSX, and there would be an equivalently simple Windows incantation. I can produce a PR, but this would probably conflict with Windows builds, and the PR is pretty much stated above anyway ;-)

**Comment by ocefpaf** [comment]
@jgomezdans we have [spatialite](https://github.com/conda-forge/gdal-feedstock/blob/gdal_1.x/recipe/build.sh#L32) support in the `gdal 1.11.x` branch and I recall testing sqlite3 and failing (don't remember the failure so I should try again.)

I will put a PR to add both to `gdal 2` as well.

**Comment by jgomezdans** [comment]
So I tried those two changes on gdal2 and "it works for me on Linux". Don't know about OSX or Windows though...

**Comment by ocefpaf** [comment]
Want to send a PR :grin: (Maybe also add yourself as a maintainer :wink:)

**Comment by jgomezdans** [comment]
Forgot to close the issue. It's been solved by merging #68 .
