### ISSUE TITLE
Remove storage of artifacts

### ISSUE THREAD

**Issue by akrherz** [conda-forge/gdal-feedstock#664]
I was about to remove the storage of artifacts, but then I thought that those could be very handy when something goes wrong, so shall we keep it for a build or two?

_Originally posted by @zklaus in https://github.com/conda-forge/gdal-feedstock/issues/651#issuecomment-1316567512_

**Comment by xylar** [comment]
It looks like bot PRs are going to try to remove the artifacts each time.  See #676.
