### ISSUE TITLE
Problems with GDAL linking on OSX

### ISSUE THREAD

**Issue by gillins** [conda-forge/gdal-feedstock#72]
I'm getting random crashes when running code that uses the latest version of GDAL on OSX. (actually the https://github.com/conda-forge/rios-feedstock test script). 

Code runs fine with earlier versions. 

I suspect this is the same problem @danclewley reported to me earlier. Some libraries are built against `/usr/lib/libstdc++` and some against Conda's `libstdc++`. I think this is due to some packages requiring libgcc (ie giflib - https://github.com/conda-forge/giflib-feedstock/pull/2 and libspatialite). 

Multiple runtime libs sounds a recipe for disaster...

Can we remove the dependency on `libgcc` easily?

@danclewley : can you confirm that the RIOS test script works fine with your `libgcc`-less versions of `gif` and `spatialite`?

**Comment by danclewley** [comment]
Using local builds of `giflib` and `spatiallite` I created without `libgcc` didn't work as `libgcc` is still being pulled in through `openblas`, which is required by the version of `numpy` which RIOS pulls in.

Removing `numpy` from the `rios` dependencies fixed this and it pulled in the same version of `numpy` `gdal` was build against (1.11.0 mkl). @gillins I'm not sure if removing `numpy` from the `rios` recipie is worth doing as it will be pulled in through `gdal` anyway.

Without `libgcc` all the `rios` tests ran fine.

**Comment by ocefpaf** [comment]
> Can we remove the dependency on `libgcc` easily?

From `giflib` yes, from `spatiallite`, not sure... I will take a look.

>  I created without `libgcc` didn't work as `libgcc` is still being pulled in through `openblas`, which is required by the version of `numpy` which RIOS pulls in.

I believe we can specify `numpy` with `mkl` in the recipe. I just forgot the syntax :grimacing:

**Comment by ocefpaf** [comment]
> from `spatiallite`, not sure... I will take a look.

I guess we are OK dropping `libgcc` for `spatialite` too. (See https://github.com/conda-forge/libspatialite-feedstock/pull/8)

If you are OK becoming maintainers of `libspatialite` I can merge as-is, if not I will remove you from the list and merge so we can move forward with `rios`.

**Comment by pelson** [comment]
Openblas and scipy both no longer depend on `gcc` and should be free from libstdc++ contamination at this point.

**Comment by gillins** [comment]
All appears to be resolved now - thanks to all.
