### ISSUE TITLE
Confusion of cross-platform Python

### ISSUE THREAD

**Issue by hobu** [conda-forge/gdal-feedstock#736]
The interpreter that's being substituted into the Python-based GDAL utilities like `gdal_edit.py` is cross-python, not the environment's. I suppose this was caused by GDAL changing how it grabbed the active Python environment.

```
mamba create -n gdal363 -c conda-forge gdal=3.6.3 -y
(base) hobu-mbp-14 ~ ~ % mamba activate gdal363
(gdal363) hobu-mbp-14 ~ ~ % gdal_edit.py
zsh: /Users/hobu/miniforge3/envs/gdal363/bin/gdal_edit.py: bad interpreter: /Users/runner/miniforge3/conda-bld/gdal-split_1678794200052/_build_env/venv/bin/cross-python: no such file or directory

```

https://github.com/conda-forge/gdal-feedstock/blob/main/recipe/install_python.sh#L13 doesn't appear to be passing in `CMAKE_ARGS`, so maybe this is the start.

**Comment by rouault** [comment]
> CMAKE_ARGS

it is already passed in the https://github.com/conda-forge/gdal-feedstock/blob/main/recipe/build.sh, and AFAICS we reuse the existing CMakeCache.txt for the "gdal" python sub-packages.

I'm wondering if https://github.com/conda-forge/gdal-feedstock/pull/730/files or https://github.com/conda-forge/gdal-feedstock/pull/733/files would have caused the issue., but normally the impact is just how the SWIG generated files are copied, not the GDAL scripts.
If some editing of the interpreter in GDAL utility scripts is done, it must be presumably done by the "$PYTHON setup.py build_ext" or "$PYTHON -m pip install --no-deps --ignore-installed ." step

@hobu Could you install the osx-arm64/gdal-3.6.2-pyXXXXXXX_8.conda (before PR #730) vs osx-arm64/gdal-3.6.2-pyXXXXXXX_9.conda (after PR #730) to see if that's the cause.

**Comment by hobu** [comment]
My gdal_edit.py looks like this:

```
#!/Users/runner/miniforge3/conda-bld/gdal-split_1678653675361/_build_env/venv/bin/cross-python

import sys

from osgeo.gdal import deprecation_warn

# import osgeo_utils.gdal_edit as a convenience to use as a script
from osgeo_utils.gdal_edit import *  # noqa
from osgeo_utils.gdal_edit import main

deprecation_warn("gdal_edit")
sys.exit(main(sys.argv))
```

Where in GDAL's build process does the path to the Python interpreter get substituted in? Because we're in a cross compiling scenario, the path that's available to the builder isn't actually the one we want to substitute.

**Comment by rouault** [comment]
> Where in GDAL's build process does the path to the Python interpreter get substituted in?

I've no idea... Not by GDAL itself as far as I can tell. Must be the setuptools or pip magic...

**Comment by hobu** [comment]
> @hobu Could you install the osx-arm64/gdal-3.6.2-pyXXXXXXX_8.conda (before PR https://github.com/conda-forge/gdal-feedstock/pull/730) vs osx-arm64/gdal-3.6.2-pyXXXXXXX_9.conda (after PR https://github.com/conda-forge/gdal-feedstock/pull/730) to see if that's the cause.

`_6` shows the same issue for me, so it must be before this PR. This would be a miserable bisect 😄

**Comment by rouault** [comment]
Googling a bit for setuptools and shebang subsitution leads to https://stackoverflow.com/questions/37874445/override-the-shebang-mangling-in-python-setuptools, https://github.com/pypa/setuptools/issues/494, https://github.com/debbiemarkslab/EVcouplings/pull/103/files

**Comment by gillins** [comment]
Seems GDAL still uses the old `python setup.py`(?). I think most of our things these days use `pip install .` or use `cmake` to do the install, not sure if that makes a difference. 
I'm sure there used to be a `-e` option to `python setup.py` but I can't find it now....

**Comment by rouault** [comment]
$ python setup.py build --help | grep executable
  --executable (-e)  specify final destination interpreter path (build.py)

**Comment by gillins** [comment]
That's the one!
