### ISSUE TITLE
Add support for expat

### ISSUE THREAD

**Issue by gillins** [conda-forge/gdal-feedstock#74]
As pointed out by @jakirkham, `gdal` is linked against the system `libexpat` on OSX which should be corrected. As we have a conda-forge `libexpat` we should link against that on all platforms which will give us a few more formats.

**Comment by ocefpaf** [comment]
`gdal 1.x` should be OK. I guess I made a bad job porting all the changes to `gdal 2`

https://github.com/conda-forge/gdal-feedstock/blob/gdal_1.x/recipe/build.sh#L27

PS: Sorry... Until `fiona` is not fully compatible with `gdal 2` my mind is not really there :grimacing:

**Comment by gillins** [comment]
No need to apologise! I think we are very close with `gdal 2` - we don't seem to get people complaining about missing drivers. Maybe no one is using it :wink: ?

**Comment by ocefpaf** [comment]
~80% of "my" community sends me direct e-mails. Oh how I wish they were on GitHub! (but no report on missing drivers here too)

**Comment by ocefpaf** [comment]
Added for `*nix` in #75. Not sure how to add expat on the Windows build.

**Comment by ocefpaf** [comment]
@gillins can we close this one? I believe #90 covered that, right?

**Comment by gillins** [comment]
Indeed :smile:
