### ISSUE TITLE
Build issue with libxml2 on OS X

### ISSUE THREAD

**Issue by aleksandervines** [conda-forge/gdal-feedstock#88]
For some reason (I can not figure out why), libxml2 is being installed from defaults channel (2.9.2), not conda-forge (which has 2.9.3). Setting the libxml2 2.9.3 dependency explicitly in gdal solves this issue.

Before setting dependency:
https://travis-ci.org/aleksandervines/gdal-feedstock/builds/143299375

After:
https://travis-ci.org/aleksandervines/gdal-feedstock/builds/143318936

From what I can find, only libspatialite of gdal dependencies requires libxml2, and when installing libspatialite itself it seems to use the conda-forge libxml2 (unless I have already downloaded the default one by attempting to build gdal).

**Comment by ocefpaf** [comment]
The conda solver tries to optimize the overall versions so the solution is not the same when the packages list to be installed is different. Here I believe conda is optimizing for the latest `Python`, which pulls the latest `xz` and, b/c our `libxml2` is pinned against an older `xz`, the defaults version of `libxml2` is picked.

Closing this as there is nothing we can do in `gdal` and this will go away once we update our `xz` pinings.
