### ISSUE TITLE
Symbol not found: __ZN6kealib10KEAImageIO10isKEAImageESs

### ISSUE THREAD

**Issue by BtbN** [conda-forge/gdal-feedstock#91]
This looks like gdal needs a rebuild against the latest version of kealib?

https://travis-ci.org/OGGM/OGGM-Anaconda/jobs/144452309#L1940

**Comment by ocefpaf** [comment]
@BtbN I tested this locally and it seems to be fixed with in the latest build. Let me know if you are still finding problems.
