### ISSUE TITLE
Upgrading gdal drivers in geopandas

### ISSUE THREAD

**Issue by DBaryudin** [conda-forge/gdal-feedstock#96]
The geopandas that is downloaded via "conda install geopandas" has a gdal version that does not contain all of the necessary drivers.  For example, when I run a command like "

ogrinfo input.shp -dialect SQLite -sql..." 

I get the response, "ERROR 6: The SQLite driver needs to be compiled to support the SQLite SQL dialect"

Trying to upgrade GDAL, I run into dependency issues.  If I upgrade fiona, everything breaks and geopandas can no longer interact with fiona.

Is there a way to choose the drivers to be downloaded with Conda?

**Comment by ocefpaf** [comment]
@DBaryudin I am not familiar with the SQLite driver. It will help me if you can create a full command, preferable with some of our test data or if some test data you can provide, so I can test it. Also, can you send me the results for:

```shell
conda create geopandas python=3.5 -n TEST -c conda-forge --yes
source activate TEST
conda info > debug.txt
conda list >> debug.txt
```

PS: You will find our test data [here](https://github.com/conda-forge/gdal-feedstock/tree/master/recipe).

**Comment by ocefpaf** [comment]
@DBaryudin `geopandas` was pinned to gal 1.11.x, which we do not compiled with `SQLite`, but the latest release should be compiled against `gdal 2.1.x` and that should work with `SQLite`.

Try to upgrade and let me know if this works for you.
